In [90]:
import numpy as np
import pandas as pd


# Files to Load
wsb1_data_to_load = "data/WSB_rd1_count.csv"
wsb2_data_to_load = "data/WSB_rd2_count.csv"
wsb3_data_to_load = "data/WSB_rd3_count.csv"

In [91]:
# Read the WSB_Reddit Data from 3 Saved Dataframes Files from 3 Batches of Reddit api Called
wsb_rd1 = pd.read_csv(wsb1_data_to_load)
wsb_rd2 = pd.read_csv(wsb2_data_to_load)
wsb_rd3 = pd.read_csv(wsb3_data_to_load)

- Vertical merge the above three dataframes, wsb_rd1, wsb_rd2 and wsb_rd3, for a WSB_reddits dataframe as a preparation for nlp analysis.
- Sort the dataframe in descending date order for a purpose of web display which allows about 125,000 rows so that the most recent rows meet the cut.

In [92]:
frames = [wsb_rd1, wsb_rd2, wsb_rd3]
WSB_reddits = pd.concat(frames)
WSB_reddits['date'] = pd.to_datetime(WSB_reddits.date)
WSB_reddits.sort_values('date', inplace=True)
WSB_reddits = WSB_reddits.loc[WSB_reddits['date']>'2016-01-01']
WSB_reddits = WSB_reddits.loc[WSB_reddits['text']!='[removed]']
WSB_reddits = WSB_reddits.loc[WSB_reddits['text']!='[deleted]']
WSB_reddits = WSB_reddits.loc[WSB_reddits['text'].notna()]
WSB_reddits = WSB_reddits.loc[:, ["date", "text", "favorites" ]].dropna()
WSB_reddits.sort_values(by=['date'], inplace=True, ascending=False)

WSB_reddits.head()

,date,text,favorites
583031,2021-05-01 00:47:49,$GTEH sells sinfit protein enhanced foods and ...,1
583030,2021-05-01 00:44:06,BUY ALERT! WSGF... World Series of Golfs Subsi...,1
583026,2021-05-01 00:39:23,We can keep things fresh for all with SCYX Vag...,1
583016,2021-05-01 00:21:36,I like MVIS and personally think it will rise ...,1
583002,2021-05-01 00:12:15,there is a poocoin telegram group that recentl...,1

In [93]:
WSB_reddits.to_csv('./Data/WSB_rd_count.csv', index=False)

In [94]:
reddits = WSB_reddits.text

In [95]:
# Instantiate Count Vectorizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import text 

my_additional_stop_words = ['https','rt', 'amp', 'com']

stop_words = text.ENGLISH_STOP_WORDS.union(my_additional_stop_words)
vectorizer = CountVectorizer( lowercase=True, stop_words=stop_words)

vector_text = reddits

# To actually create the vectorizer, we simply need to call fit on the text data that we wish to fix
cv_fit = vectorizer.fit_transform(vector_text)

In [96]:
words = vectorizer.vocabulary_

In [97]:
feature_names = vectorizer.get_feature_names()
feature_counts = cv_fit.sum(axis=0).A1

In [98]:
result=dict(zip(feature_names, feature_counts))
result

{'00': 7980,
 '000': 16245,
 '0000': 41,
 '00000': 98,
 '000000': 13,
 '0000000': 1,
 '00000000': 4,
 '000000000': 1,
 '000000000000000001': 1,
 '000000000000002': 1,
 '00000000009': 1,
 '0000000001': 1,
 '000000001': 1,
 '000000003880': 1,
 '000000005360924': 1,
 '00000001': 4,
 '00000003': 1,
 '00000006': 1,
 '000000093': 1,
 '0000001': 4,
 '00000011': 1,
 '000000248817000107': 1,
 '000000248818000102': 1,
 '000000248818000172': 2,
 '000000248819000090': 1,
 '00000024956': 1,
 '0000003402': 1,
 '000000496217000071': 1,
 '000000595': 1,
 '000000620120000066': 1,
 '000000857': 2,
 '000001': 15,
 '0000010011101110000001101010111111110001011101100001001111010100111000000100001110100111100101101110010011010101010011010110011001': 1,
 '00000142': 1,
 '0000016387': 1,
 '0000019': 1,
 '000001961720000191': 1,
 '000001961720000513': 1,
 '000002': 3,
 '0000032604': 1,
 '0000054': 1,
 '000006': 2,
 '000007': 2,
 '000007632119000082': 2,
 '000007800320000021': 1,
 '000007995815000035': 2,
 '00000866875': 2,
 '0000092380': 2,
 '00000g55g': 1,
 '00001': 12,
 '000010': 1,
 '0000100011100101011011001111000000010011110010100000101001110101001100001110010011010110100000100100111001101011010101111001101110': 1,
 '000011': 2,
 '000012': 3,
 '000012ca3d773a273acbac2c24f249818753bc48': 1,
 '0000137': 1,
 '000015': 1,
 '000017': 1,
 '000018': 1,
 '00001s': 1,
 '00002': 2,
 '000020': 1,
 '000020307716000013': 2,
 '000022': 2,
 '00002227': 1,
 '000027833120000002': 1,
 '000028': 3,
 '00003': 1,
 '0000315066': 6,
 '00003168': 1,
 '000032': 1,
 '000032019320000010': 1,
 '000042': 2,
 '000044': 2,
 '000047501': 1,
 '000048': 2,
 '000056': 1,
 '000057': 1,
 '000059': 5,
 '00006': 3,
 '000060': 1,
 '00006073': 2,
 '000063': 2,
 '0000701374': 1,
 '0000712771': 2,
 '0000715788': 2,
 '000073176620000006': 1,
 '000076215220000007': 2,
 '000076447820000062': 1,
 '0000779fd2ac': 1,
 '000079436720000116': 1,
 '00008': 1,
 '0000834237': 4,
 '000083423721001340': 1,
 '000085': 1,
 '0000863894': 1,
 '000087616720000118': 1,
 '0000876523': 1,
 '0000886128': 1,
 '0000886982': 1,
 '000089183920000218': 1,
 '000089183920000219': 1,
 '000089183920000220': 1,
 '000089183920000221': 1,
 '000089408116000212': 1,
 '000089418916009881': 1,
 '0000895419': 2,
 '000089541920000044': 4,
 '000089542118000603': 2,
 '000089542120000491': 1,
 '0000897448': 18,
 '000089914021000056': 3,
 '0000899243': 2,
 '000089924320020822': 2,
 '000089924320028613': 1,
 '0000905148': 3,
 '0000905718': 8,
 '000090571820000734': 2,
 '000090571820000859': 2,
 '000090571820001111': 13,
 '000090571821000248': 3,
 '0000919574': 2,
 '000091957417004910': 1,
 '000092': 4,
 '000092189520001273': 2,
 '000092189520002554': 1,
 '00009262': 1,
 '000093041309002195': 6,
 '0000944809': 3,
 '0000945436': 1,
 '0000946': 2,
 '0000950123': 1,
 '000095014220000972': 1,
 '000095015720000709': 2,
 '0001': 78,
 '0001001601': 1,
 '0001002135': 4,
 '0001003078': 1,
 '000100307820000182': 1,
 '0001004980': 1,
 '0001006249': 6,
 '0001013594': 1,
 '000101359420000699': 5,
 '000101359420000821': 6,
 '000101872420000004': 1,
 '000101872421000004': 1,
 '0001020859': 2,
 '000102085920000064': 1,
 '0001024305': 1,
 '000102430516000181': 1,
 '000104581016000358': 1,
 '000104631120000041': 1,
 '0001047469': 4,
 '000104746911001913': 1,
 '000104746918003703': 2,
 '000104746918003716': 2,
 '000104746918006818': 2,
 '000104746920000166': 1,
 '000104746920000860': 2,
 '000104746920002928': 2,
 '000104746920003416': 2,
 '000104746920004008': 1,
 '0001055726': 2,
 '0001062993': 2,
 '000106528020000450': 2,
 '0001067983': 1,
 '000107023521000005': 2,
 '000107553120000011': 1,
 '000107553120000027': 2,
 '0001079973': 1,
 '000107997319000239': 1,
 '0001085146': 4,
 '000108636417000005': 2,
 '000108636417000052': 2,
 '000108636417000069': 4,
 '0001091': 2,
 '0001093691': 3,
 '0001104659': 21,
 '000110465918063819': 2,
 '000110465920015273': 2,
 '000110465920030651': 1,
 '000110465920032214': 1,
 '000110465920036907': 1,
 '000110465920056601': 2,
 '000110465920073000': 1,
 '000110465920073132': 2,
 '000110465920075778': 1,
 '000110465920092733': 2,
 '000110465920105060': 2,
 '000110465920106485': 2,
 '000110465920107856': 2,
 '000110465920111952': 1,
 '000110465920114508': 2,
 '000110465920118933': 1,
 '000110465920126927': 2,
 '000110465920128504': 1,
 '000110465920129560': 1,
 '000110465920129710': 2,
 '000110465920129873': 1,
 '000110465920131626': 2,
 '000110465921001786': 1,
 '000110465921001951': 6,
 '000110465921002757': 5,
 '000110465921003837': 1,
 '000110465921004866': 2,
 '000110465921006891': 2,
 '000110465921042507': 2,
 '000110465921049151': 2,
 '000112760220017220': 1,
 '0001135185': 1,
 '000114036116057556': 1,
 '000114036119010234': 2,
 '000114036120010472': 1,
 '0001144204': 2,
 '000114420416074405': 1,
 '000114420416112818': 1,
 '000114420416115004': 1,
 '000114420416115008': 1,
 '000114420416127762': 2,
 '000114420416132525': 1,
 '000114420417001261': 1,
 '000114420417043378': 2,
 '000114420417044736': 2,
 '000114420418029491': 2,
 '000114420418041968': 1,
 '000114420419019342': 1,
 '000114420419034053': 1,
 '000114618420000006': 4,
 '0001166126': 4,
 '0001171200': 1,
 '000117120020000330': 1,
 '000117120020000357': 1,
 '000117266119001771': 2,
 '000117266119002217': 2,
 '000117492219000115': 1,
 '000117911020005143': 2,
 '0001185185': 5,
 '000119': 1,
 '0001193125': 25,
 '000119312505127244': 1,
 '000119312506063079': 1,
 '000119312508042139': 1,
 '000119312508060572': 2,
 '000119312510017054': 1,
 '000119312513144211': 2,
 '000119312513148318': 2,
 '000119312513364182': 2,
 '000119312514124006': 1,
 '000119312514364676': 1,
 '000119312515093802': 1,
 '000119312516733893': 1,
 '000119312516759308': 1,
 '000119312516793029': 2,
 '000119312517027960': 1,
 '000119312517029199': 1,
 '000119312517141291': 1,
 '000119312517219877': 1,
 '000119312517291352': 1,
 '000119312518055809': 1,
 '000119312518072253': 1,
 '000119312518099555': 1,
 '000119312518213468': 1,
 '000119312518261892': 1,
 '000119312518278524': 1,
 '000119312518341244': 1,
 '000119312519095913': 1,
 '000119312519222176': 2,
 '000119312519227993': 1,
 '000119312519235734': 2,
 '000119312519264113': 2,
 '000119312519294656': 4,
 '000119312520005504': 1,
 '000119312520038372': 1,
 '000119312520044221': 1,
 '000119312520064645': 2,
 '000119312520080819': 1,
 '000119312520093737': 1,
 '000119312520097205': 4,
 '000119312520098060': 2,
 '000119312520118310': 2,
 '000119312520140451': 1,
 '000119312520157158': 1,
 '000119312520174043': 1,
 '000119312520175042': 2,
 '000119312520175997': 1,
 '000119312520191638': 2,
 '000119312520191966': 3,
 '000119312520198619': 2,
 '000119312520227100': 4,
 '000119312520227516': 4,
 '000119312520230013': 5,
 '000119312520250103': 3,
 '000119312520251336': 1,
 '000119312520251763': 2,
 '000119312520257973': 2,
 '000119312520268504': 2,
 '000119312520290474': 1,
 '000119312520290490': 1,
 '000119312520292381': 7,
 '000119312520294801': 8,
 '000119312520296650': 2,
 '000119312520298230': 3,
 '000119312520298630': 3,
 '000119312520299507': 1,
 '000119312520306257': 2,
 '000119312520309831': 1,
 '000119312520311265': 1,
 '000119312520312805': 7,
 '000119312520313884': 2,
 '000119312520318610': 1,
 '000119312520319074': 1,
 '000119312520326213': 2,
 '000119312520329909': 2,
 '000119312521011458': 2,
 '000119312521012712': 2,
 '000119312521013558': 2,
 '000119312521019848': 1,
 '000119312521041777': 2,
 '000119312521042132': 1,
 '000119312521045839': 1,
 '000119312521055870': 1,
 '000119312521091150': 2,
 '000119312521094920': 1,
 '000119312521095509': 4,
 '000119312521102551': 4,
 '000119312521104220': 4,
 '000119312521105223': 2,
 '000119312521107765': 4,
 '000119380520001571': 5,
 '000120677415003398': 1,
 '000120919120043419': 2,
 '000120919120061332': 1,
 '0001213900': 33,
 '000121390018001442': 2,
 '000121390018001857': 1,
 '000121390018004551': 2,
 '000121390018007523': 1,
 '000121390018014480': 1,
 '000121390019003643': 2,
 '000121390019004056': 3,
 '000121390019007779': 1,
 '000121390020012047': 1,
 '000121390020013714': 2,
 '000121390020015000': 1,
 '000121390020015311': 2,
 '000121390020017648': 1,
 '000121390020018987': 1,
 '000121390020021307': 2,
 '000121390020021459': 1,
 '000121390020022607': 1,
 '000121390020022608': 2,
 '000121390020022997': 2,
 '000121390020028176': 1,
 '000121390020030403': 2,
 '000121390020033714': 1,
 '000121390020034230': 1,
 '000121390020038639': 1,
 '000121390020039415': 1,
 '000121390020039646': 2,
 '000121390020041124': 1,
 '000121390021001584': 1,
 '000121390021004046': 1,
 '000121390021019641': 2,
 '000121465918003426': 1,
 '000121465920006149': 1,
 '000121465920007479': 2,
 '000122520819002329': 1,
 '000122520820010740': 1,
 '000122520820010741': 1,
 '000122520820010742': 1,
 '000122520820010743': 1,
 '000122520820010744': 1,
 '000122520820010745': 1,
 '000122520820010746': 1,
 '000122520820010747': 1,
 '000123027618000045': 1,
 '000125': 1,
 '0001255159': 2,
 '000125547420000011': 1,
 '000127956920001447': 2,
 '0001284170': 24,
 '0001298': 2,
 '000129993314001918': 1,
 '0001318605': 2,
 '0001321655': 5,
 '0001326380': 4,
 '000132638020000119': 2,
 '000132638020000134': 3,
 '000132638021000006': 1,
 '000132638021000017': 1,
 '000132638021000018': 3,
 '0001335258': 6,
 '000133525820000028': 1,
 '0001354457': 3,
 '000135445720000339': 1,
 '000135445721000313': 1,
 '000135445721000511': 3,
 '0001364742': 10,
 '000136495418000187': 1,
 '000136495420000108': 1,
 '000136836520000028': 1,
 '00013706': 2,
 '0001387131': 1,
 '000138713120000238': 1,
 '000138713121001680': 2,
 '000139111709000007': 2,
 '0001392694': 1,
 '00014': 4,
 '0001411579': 30,
 '0001437749': 8,
 '000143774920007710': 1,
 '000144702820000078': 2,
 '000144759920000051': 1,
 '0001468174': 1,
 '000146817420000015': 1,
 '000146866620000019': 1,
 '0001472225': 4,
 '000147733320000004': 1,
 '0001477932': 2,
 '0001483934': 1,
 '0001493152': 5,
 '000149315216009538': 1,
 '000149315217001256': 1,
 '000149315220008931': 2,
 '000149315220012247': 1,
 '000149315221001336': 1,
 '000149315221006917': 2,
 '000149315221007532': 4,
 '0001499275': 2,
 '000149927521000006': 1,
 '00015': 2,
 '00015029': 1,
 '0001512282': 2,
 '000151741320000244': 2,
 '000152435820000011': 1,
 '000152435820000029': 1,
 '000153072120000062': 2,
 '0001533998': 4,
 '000153641118000008': 2,
 '0001543151': 6,
 '00015554ebb9f628789f1c3120b1e4145df851a1': 1,
 '0001558370': 8,
 '000155837016003688': 2,
 '000155837019011376': 1,
 '000155837020011097': 2,
 '000155837020013381': 1,
 '0001559720': 1,
 '000156': 2,
 '0001561014': 3,
 '0001564408': 2,
 '0001564590': 6,
 '000156459014000667': 1,
 '000156459015005237': 1,
 '000156459015010758': 1,
 '000156459016013394': 1,
 '000156459016014867': 2,
 '000156459017010357': 1,
 '000156459018007226': 1,
 '000156459018015288': 1,
 '000156459018023704': 2,
 '000156459019009195': 2,
 '000156459019031492': 2,
 '000156459019038256': 1,
 '000156459019041878': 2,
 '000156459020002450': 1,
 '000156459020014358': 2,
 '000156459020032134': 2,
 '000156459020038994': 1,
 '000156459020042442': 2,
 '000156459020053193': 2,
 '000156459021009913': 2,
 '000156459021010584': 2,
 '000156459021012981': 4,
 '000156459021021567': 6,
 '000156459021021572': 12,
 '0001564902': 1,
 '0001567619': 10,
 '000156761919021303': 2,
 '000156761920012703': 2,
 '000156761920019679': 8,
 '000156761921003819': 3,
 '000156821421000007': 1,
 '000156821421000010': 1,
 '000156821421000011': 1,
 '0001569568': 2,
 '0001575705': 4,
 '0001576942': 6,
 '0001578684': 1,
 '0001580864': 2,
 '0001582202': 1,
 '0001585521': 2,
 '000158552120000233': 1,
 '0001594805': 1,
 '000160706215000089': 2,
 '000161417818000349': 1,
 '0001616683': 2,
 '0001628110': 4,
 '0001628280': 12,
 '000162828018012674': 1,
 '000162828019013414': 1,
 '000162828019014511': 1,
 '000162828019015006': 1,
 '000162828020002318': 1,
 '000162828020013010': 1,
 '000162828020013667': 2,
 '000162828020013900': 2,
 '000162828020016443': 3,
 '000162828020016866': 2,
 '000162828020017451': 2,
 '000162828021004565': 2,
 '0001637529': 4,
 '0001640147': 2,
 '0001640334': 2,
 '0001643953': 1,
 '000165204420000008': 1,
 '000165260820000003': 1,
 '0001654954': 3,
 '000165495419007798': 1,
 '000165495420013699': 1,
 '0001661964': 1,
 '0001663577': 1,
 '000168316820002123': 2,
 '000169082017000007': 1,
 '000169985': 1,
 '00017': 1,
 '000170': 2,
 '000172': 2,
 '0001728949': 2,
 '0001731289': 3,
 '000173128920000012': 2,
 '0001740332': 2,
 '000174211442': 2,
 '0001743344': 1,
 '000174373619000002': 4,
 '0001745916': 1,
 '0001754778': 1,
 '000175707319000028': 2,
 '0001766600': 2,
 '0001774263': 4,
 '00017773': 1,
 '00017900': 1,
 '0001792789': 2,
 '000179955120000060': 2,
 '000179955120000061': 2,
 '000179955120000062': 2,
 '000179955120000063': 2,
 '000179955120000064': 2,
 '0001805284': 2,
 '000180709420000005': 2,
 '000181': 1,
 '0001813446': 4,
 '0001813756': 8,
 '000182': 1,
 '000182072120000007': 1,
 '0001834584': 2,
 '00018ddfb463f7bb33cb8ea49ea55fb6fc7b8831': 1,
 '0001x': 1,
 '0002': 20,
 '000200': 2,
 '00021b9ffc437efbc220a02f1b2d62315b5bec33': 1,
 '000230': 1,
 '000239': 1,
 '000242': 4,
 '000248': 3,
 '00025': 1,
 '00026': 1,
 '00027': 1,
 '000274': 1,
 '0003': 10,
 '000305899': 1,
 '00031': 1,
 '0003104389': 1,
 '00032084': 1,
 '00033': 4,
 '000330': 1,
 '000339': 1,
 '00034': 1,
 '000343': 1,
 '0004': 8,
 '00041700117': 1,
 '000420': 1,
 '00043': 1,
 '00044088': 1,
 '00045217': 2,
 '00045471': 1,
 '000457': 2,
 '0004620198': 2,
 '000491': 1,
 '0005': 24,
 '000500579': 1,
 '000518': 2,
 '000563': 2,
 '0005d26917b8d3a1d45302504f0a950f35fce56f': 1,
 '0006': 6,
 '000660': 1,
 '000699': 1,
 '0006e34b380cfba161654f59231aedbafac1e124': 1,
 '0007': 3,
 '00072': 1,
 '00073': 2,
 '00075': 1,
 '00076947': 1,
 '00078': 1,
 '0007cbca1a994e93cb20ee259a1b4e672573961f': 1,
 '0008': 2,
 '00084': 1,
 '00089': 1,
 '0009': 6,
 '000900882': 4,
 '000906': 1,
 '00093': 1,
 '000950': 1,
 '000951': 1,
 '000953': 1,
 '00097': 1,
 '000977': 1,
 '000988': 1,
 '00099': 2,
 '000_profit_in_stock_picks': 1,
 '000al7ru3ms': 1,
 '000aud': 1,
 '000bce': 1,
 '000c': 13,
 '000c80': 1,
 '000dhs': 2,
 '000dol': 1,
 '000e61293b337ac5b2ba02e155bb4da7fdd8e0f1': 1,
 '000eur': 1,
 '000ft': 2,
 '000g': 47,
 '000gh': 1,
 '000grams': 1,
 '000gvw': 1,
 '000infinity': 1,
 '000ish': 3,
 '000k': 17,
 '000kg': 9,
 '000kgs': 3,
 '000kr': 1,
 '000lb': 2,
 '000lbs': 1,
 '000m': 2,
 '000mg': 1,
 '000mt': 1,
 '000nok': 2,
 '000p': 3,
 '000percent': 1,
 '000rmb': 1,
 '000s': 24,
 '000sf': 1,
 '000shares': 1,
 '000sq': 2,
 '000sqft': 3,
 '000t': 6,
 '000th': 16,
 '000therefore': 1,
 '000usd': 9,
 '000volume': 1,
 '000x': 12,
 '000x100': 1,
 '000z': 1,
 '000ª': 1,
 '001': 159,
 '0010': 8,
 '00100000': 11,
 '0010001011010110011110011010111001110100101101011001100001010110011111101110101101111101010011101001011110111100000101100001111000': 1,
 '001007': 1,
 '0010100010000001010011001011001110001101110101110010101011110111101011100010100001010010110100010100001010010110111110001100111111': 1,
 '0010110011101001011011110000010100011100010010000010000000011100111100011110001111011110000101000010100100011111101110001010100111': 1,
 '001046': 1,
 '001050': 5,
 '0010694293591779': 1,
 '0011': 5,
 '001100': 1,
 '00110000': 44,
 '00110001': 36,
 '0011001010001110010001101010010000010100011101001111001101111110010101100010100010011001101001010101101011110001010010111101011111': 1,
 '0011010000001000111110100010100001111010101101011110011111010110011011101000011000101011011100110100011010101000001010000100101000': 1,
 '0011011010000010010100101001100011011011110101100111100111111011011110110000010111001110010000000001100111000010100111101010000101': 1,
 '001105302020': 1,
 '0011100101001010010001110111100000001010011100001010100001010011000000110001110100101101101011101001011100011010100000001100111001': 1,
 '0011101010000100100110010100011111110100111110110111100011001011001101000110000000001101111100100110001111110100111000101100101010': 1,
 '001111': 5,
 '001111001': 1,
 '0011111111111110111010010001011011100000101001010011111001000110000101000101000100010100011111010100110010110011001110111011100110': 1,
 '00115': 1,
 '0012': 9,
 '0012dae95655af6b42d1dc1e065f6276637c45d3': 1,
 '0013': 5,
 '001300p': 1,
 '001309823': 1,
 '001327': 4,
 '001348': 1,
 '001389': 1,
 '0014': 10,
 '00142792bfaf9dc8db3f94e9cbb47e10e392071b': 1,
 '001441563': 1,
 '00144feabdc0': 3,
 '00145': 2,
 '00148': 1,
 '0015': 9,
 '001502573': 1,
 '00155': 1,
 '0016': 3,
 '0017': 9,
 '00171e537864d56e32ad416a19153174c8c9cd14': 1,
 '00174': 1,
 '0018': 3,
 '001804': 4,
 '00181': 2,
 '001812296': 4,
 '001817': 1,
 '001884': 2,
 '0019': 1,
 '001972': 1,
 '001c5d85d50818ebefee2f74154c8c4468d216bd': 1,
 '001e165cabb4e512ee64e19888c5090622b790d6': 1,
 '001market': 1,
 '001mm': 1,
 '001s1': 2,
 '001sfte': 1,
 '002': 56,
 '0020': 2,
 '002053': 1,
 '002062116_2013_0001_ac': 1,
 '0021': 1,
 '00211': 1,
 '00214': 1,
 '00216': 1,
 '0021f22ff10f594e87c0c208d2d3a938d94813b3': 1,
 '0021fdcab5d16ca2ba1c5e57507c2128abf28b43': 1,
 '0022': 3,
 '002281': 1,
 '0023': 1,
 '002352': 2,
 '00236': 1,
 '002371': 1,
 '002392': 2,
 '00239d43b35be1f158734b19e14fedb4be05bcf2': 1,
 '00239fa00d74': 1,
 '0024': 1,
 '002459649': 1,
 '002460': 1,
 '002468': 2,
 '002473': 1,
 '0024f034748a3de12e43763bfc7c639543f2792d': 1,
 '0025': 4,
 '0026': 1,
 '00269': 1,
 '0026b9414f30': 1,
 '0027': 4,
 '00273': 1,
 '0028': 1,
 '0029': 2,
 '00292': 1,
 '002920': 1,
 '00293255131956': 1,
 '002_12_month_results_final': 1,
 '002b': 1,
 '002c7ff93n': 1,
 '002ip6': 1,
 '002isl': 1,
 '002ism': 2,
 '002v': 2,
 '003': 79,
 '0030': 1,
 '003001950': 2,
 '003121499': 1,
 '0032682d4cc16c567c42de0a137846dd393c685e': 1,
 '00329590': 1,
 '0033': 2,
 '003337418': 1,
 '0034': 4,
 '00341': 1,
 '0035': 10,
 '003530': 1,
 '00355': 2,
 '0036': 2,
 '003604': 2,
 '0037': 1,
 '003706cb70a1': 2,
 '003743': 2,
 '0038': 1,
 '003823': 2,
 '00385a828675e4e11333203d6dbf040115256e1e': 1,
 '0039': 4,
 '00390': 1,
 '003936899': 1,
 '003958473': 8,
 '00396': 1,
 '003a557f185405785c2b7c6a29c54c2882a23a2d': 1,
 '003b': 2,
 '004': 58,
 '004000': 1,
 '004099': 4,
 '0041': 3,
 '004100120': 1,
 '004198': 1,
 '0042': 2,
 '0042069': 1,
 '00427b11d00f097fcf299590991dc0ae82b62196': 1,
 '0043': 3,
 '00432': 1,
 '00434': 8,
 '004456': 2,
 '0045': 8,
 '00457': 1,
 '004596': 2,
 '0046': 4,
 '004654': 2,
 '0047': 1,
 '00473': 1,
 '00479': 2,
 '0048': 1,
 '00484': 1,
 '00493d0cc9e570dee2d63c81858d29c760da7198': 1,
 '00497': 1,
 '004bbe57cf10e7d1c0d7f4ee87aae9374ee37572': 1,
 '004e995f': 1,
 '004k': 2,
 '005': 96,
 '0050': 3,
 '005000722': 2,
 '00501p': 1,
 '00506': 1,
 '0050b8800076c157d699e2dd1cfe8ad97015ef15': 1,
 '0051b255': 1,
 '0052': 7,
 '005213': 1,
 '0052285a3da1637689665e1708d86cf482402877': 1,
 '005380': 1,
 '0054': 2,
 '005404368': 2,
 '005432001': 1,
 '0054cd56bde8746f1aa837260962287b58fcf80d': 1,
 '0055': 4,
 '005502745': 1,
 '00556': 1,
 '00559': 4,
 '0056': 3,
 '00560784x': 1,
 '005612811': 1,
 '005621030': 1,
 '00564': 1,
 '005646': 2,
 '005829276b4503e6d95c651b23cfc410d775b936': 1,
 '00592': 1,
 '005930': 3,
 '005972': 2,
 '005977': 1,
 '005b': 1,
 '005bd6c3156a79eeab3d4ec007858cb6efb94c73': 1,
 '005cc082f0c2635147b428f85d6a0119569c24c7': 1,
 '005ccd498604e7f9fe60d63a6d74e77f5e6ed9e1': 1,
 '005ef2b8eee58d136852a84d8b969502823e10a9': 1,
 '006': 32,
 '0060': 1,
 '00600': 1,
 '0060555661': 1,
 '0061': 1,
 '00612': 1,
 '0062': 2,
 '00622': 2,
 '0062950618749d315101fb97d09237db961e2d40': 1,
 '00637': 2,
 '0064': 2,
 '006400': 1,
 '0065': 1,
 '00650b5ee6c59cdd4075052f3f51de544776e2c9': 1,
 '0066': 1,
 '0067': 1,
 '00672': 1,
 '00677': 1,
 '0067e3d6e48e4eb63c3188743d360db9a8b949f2': 1,
 '0068': 1,
 '00689': 1,
 '0068fd8ddca0862ab680d396c212aa87614242db': 1,
 '0069': 4,
 '006a12abd765c745f77066204504ecce401f925c': 1,
 '006af82dbb4374f6449dbe2e978e911a89a65002': 1,
 '006cd3c6bb59a744e90351e26a00c9be58c7a83b': 1,
 '006cm': 1,
 '006mb': 1,
 '007': 44,
 '0070': 1,
 '00700': 3,
 '0071': 1,

In [99]:
final_count_df = pd.DataFrame({"word": feature_names, "cnt_word": feature_counts})
final_count_df.sort_values(by='cnt_word', ascending=False)

           word  cnt_word
173362     just     80484
240827    stock     79454
186557   market     75627
181265     like     73419
89386       buy     63106
...         ...       ...
147841   gbmzxs         1
147842   gbn13d         1
147843   gbn400         1
147844   gbn5we         1
138326  fotjjnr         1

[276653 rows x 2 columns]

In [100]:
# Introduce adjusted economic keywords extracted from top 100 words in the combolist in Powell's speeches + keywords in economic indicators
trade_matchers = ["bankruptcies",
"broadband internet penetration",
"building permit",
"business cycle",
"central banks",
"changes in",
"china",
"construction spending",
"consumer confidence index",
"consumer leverage ratio",
"consumer price index",
"consumer spending",
"during the",
"economic growth",
"employment",
"export",
"federal funds",
"federal open",
"federal reserve",
"financial crisis",
"financial stability",
"financial system",
"forward to",
"funds rate",
"gdp",
"home building",
"housing starts",
"import",
"importance of",
"industrial production",
"inflation",
"interest rate spread",
"interest rates",
"jobless claims",
"labor market",
"level of",
"likely to",
"longer term",
"look forward",
"manufacture new order",
"manufacture",
"manufacturing demand",
"manufacturing",
"market committee",
"market",
"maximum employment",
"monetary policy",
"money supply",
"money",
"monthly job added",
"NAFTA",
"NASDAQ",
"need to",
"new residential sales",
"oil",
"open market",
"opportunity to",
"our percent",
"over time",
"percent objective",
"prime rate",
"producer price index",
"quarterly change in gdp",
"retail sales",
"review of",
"S&P 500",
"short term",
"stock market prices",
"stock market",
"stocks",
"tariff",
"tax",
"the committee",
"the economy",
"the fed",
"the federal",
"the fomc",
"the great",
"the outlook",
"the united",
"the world",
"to address",
"to continue",
"to ensure",
"to help",
"to make",
"to provide",
"to speak",
"to support",
"trade",
"turn to",
"understanding of",
"unemployment",
"united states",
"vendor performance",
"weekly hours",
"wholesale price index"]

In [101]:
import datetime
from collections import defaultdict
import numpy as np

In [102]:
WSB_reddits['week'] = (WSB_reddits.date - WSB_reddits['date'].dt.weekday * np.timedelta64(1,'D'))
WSB_reddits['week'] = pd.DatetimeIndex(WSB_reddits['week']).normalize()
WSB_reddits['day'] = pd.DatetimeIndex(WSB_reddits['date']).normalize()
WSB_reddits

,date,text,favorites,week,day
583031,2021-05-01 00:47:49,$GTEH sells sinfit protein enhanced foods and ...,1,2021-04-26,2021-05-01
583030,2021-05-01 00:44:06,BUY ALERT! WSGF... World Series of Golfs Subsi...,1,2021-04-26,2021-05-01
583026,2021-05-01 00:39:23,We can keep things fresh for all with SCYX Vag...,1,2021-04-26,2021-05-01
583016,2021-05-01 00:21:36,I like MVIS and personally think it will rise ...,1,2021-04-26,2021-05-01
583002,2021-05-01 00:12:15,there is a poocoin telegram group that recentl...,1,2021-04-26,2021-05-01
...,...,...,...,...,...
34,2016-01-01 21:10:15,Twice as much gainz over the last 10 years. T...,1,2015-12-28,2016-01-01
33,2016-01-01 18:58:08,I noticed they bought out optionsexpress Canad...,1,2015-12-28,2016-01-01
32,2016-01-01 18:02:39,They have recently acquiered SNDK and their on...,0,2015-12-28,2016-01-01
28,2016-01-01 03:41:28,I believe stock has potential for a break out ...,8,2015-12-28,2016-01-01
27,2016-01-01 01:16:00,I'm confused about which would be the better t...,2,2015-12-28,2016-01-01

In [103]:
# Count frequencies of economic keywords by week
countbyweek=defaultdict(int)
for index,row in WSB_reddits.iterrows():
    for word in range(len(row['text'].split(' '))-1):
        words = row['text'].split(' ')
        if f'{words[word]} {words[word +1]}' in trade_matchers:
            countbyweek[row['week']] += 1
#     break
countbyweek

defaultdict(int,
            {Timestamp('2021-04-26 00:00:00'): 591,
             Timestamp('2021-04-19 00:00:00'): 559,
             Timestamp('2021-04-12 00:00:00'): 514,
             Timestamp('2021-04-05 00:00:00'): 720,
             Timestamp('2021-03-29 00:00:00'): 965,
             Timestamp('2021-03-22 00:00:00'): 76,
             Timestamp('2021-03-15 00:00:00'): 802,
             Timestamp('2021-03-08 00:00:00'): 2351,
             Timestamp('2021-03-01 00:00:00'): 688,
             Timestamp('2021-02-22 00:00:00'): 842,
             Timestamp('2021-02-15 00:00:00'): 1345,
             Timestamp('2021-02-08 00:00:00'): 904,
             Timestamp('2021-02-01 00:00:00'): 1871,
             Timestamp('2021-01-25 00:00:00'): 6292,
             Timestamp('2021-01-18 00:00:00'): 1243,
             Timestamp('2021-01-11 00:00:00'): 726,
             Timestamp('2021-01-04 00:00:00'): 483,
             Timestamp('2020-12-28 00:00:00'): 527,
             Timestamp('2020-12-21 00:00:00'): 487,
             Timestamp('2020-12-14 00:00:00'): 423,
             Timestamp('2020-12-07 00:00:00'): 643,
             Timestamp('2020-11-30 00:00:00'): 776,
             Timestamp('2020-11-23 00:00:00'): 814,
             Timestamp('2020-11-16 00:00:00'): 365,
             Timestamp('2020-11-09 00:00:00'): 304,
             Timestamp('2020-11-02 00:00:00'): 191,
             Timestamp('2020-10-26 00:00:00'): 315,
             Timestamp('2020-10-19 00:00:00'): 330,
             Timestamp('2020-10-12 00:00:00'): 409,
             Timestamp('2020-10-05 00:00:00'): 350,
             Timestamp('2020-09-28 00:00:00'): 329,
             Timestamp('2020-09-21 00:00:00'): 431,
             Timestamp('2020-09-14 00:00:00'): 415,
             Timestamp('2020-09-07 00:00:00'): 415,
             Timestamp('2020-08-31 00:00:00'): 633,
             Timestamp('2020-08-24 00:00:00'): 469,
             Timestamp('2020-08-17 00:00:00'): 413,
             Timestamp('2020-08-10 00:00:00'): 418,
             Timestamp('2020-08-03 00:00:00'): 479,
             Timestamp('2020-07-27 00:00:00'): 448,
             Timestamp('2020-07-20 00:00:00'): 279,
             Timestamp('2020-07-13 00:00:00'): 412,
             Timestamp('2020-07-06 00:00:00'): 421,
             Timestamp('2020-06-29 00:00:00'): 322,
             Timestamp('2020-06-22 00:00:00'): 422,
             Timestamp('2020-06-15 00:00:00'): 591,
             Timestamp('2020-06-08 00:00:00'): 354,
             Timestamp('2020-06-01 00:00:00'): 238,
             Timestamp('2020-05-25 00:00:00'): 493,
             Timestamp('2020-05-18 00:00:00'): 538,
             Timestamp('2020-05-11 00:00:00'): 480,
             Timestamp('2020-05-04 00:00:00'): 631,
             Timestamp('2020-04-27 00:00:00'): 676,
             Timestamp('2020-04-20 00:00:00'): 752,
             Timestamp('2020-04-13 00:00:00'): 707,
             Timestamp('2020-04-06 00:00:00'): 914,
             Timestamp('2020-03-30 00:00:00'): 691,
             Timestamp('2020-03-23 00:00:00'): 904,
             Timestamp('2020-03-16 00:00:00'): 1118,
             Timestamp('2020-03-09 00:00:00'): 963,
             Timestamp('2020-03-02 00:00:00'): 697,
             Timestamp('2020-02-24 00:00:00'): 697,
             Timestamp('2020-02-17 00:00:00'): 400,
             Timestamp('2020-02-10 00:00:00'): 356,
             Timestamp('2020-02-03 00:00:00'): 313,
             Timestamp('2020-01-27 00:00:00'): 323,
             Timestamp('2020-01-20 00:00:00'): 241,
             Timestamp('2020-01-13 00:00:00'): 197,
             Timestamp('2020-01-06 00:00:00'): 160,
             Timestamp('2019-12-30 00:00:00'): 172,
             Timestamp('2019-12-23 00:00:00'): 85,
             Timestamp('2019-12-16 00:00:00'): 112,
             Timestamp('2019-12-09 00:00:00'): 98,
             Timestamp('2019-12-02 00:00:00'): 164,
             Timestamp('2019-11-25 00:00:00'): 123,
             Timestamp('2019-11-18 00:00:00'): 118,
             Timestamp('2019-11-11 00:00:00'): 148,
             Timestamp('2019-11-04 00:00:00'): 177,
             Timestamp('2019-10-28 00:00:00'): 108,
             Timestamp('2019-10-21 00:00:00'): 132,
             Timestamp('2019-10-14 00:00:00'): 132,
             Timestamp('2019-10-07 00:00:00'): 128,
             Timestamp('2019-09-30 00:00:00'): 96,
             Timestamp('2019-09-23 00:00:00'): 100,
             Timestamp('2019-09-16 00:00:00'): 120,
             Timestamp('2019-09-09 00:00:00'): 150,
             Timestamp('2019-09-02 00:00:00'): 93,
             Timestamp('2019-08-26 00:00:00'): 128,
             Timestamp('2019-08-19 00:00:00'): 189,
             Timestamp('2019-08-12 00:00:00'): 267,
             Timestamp('2019-08-05 00:00:00'): 120,
             Timestamp('2019-07-29 00:00:00'): 132,
             Timestamp('2019-07-22 00:00:00'): 107,
             Timestamp('2019-07-15 00:00:00'): 120,
             Timestamp('2019-07-08 00:00:00'): 102,
             Timestamp('2019-07-01 00:00:00'): 72,
             Timestamp('2019-06-24 00:00:00'): 74,
             Timestamp('2019-06-17 00:00:00'): 81,
             Timestamp('2019-06-10 00:00:00'): 94,
             Timestamp('2019-06-03 00:00:00'): 118,
             Timestamp('2019-05-27 00:00:00'): 128,
             Timestamp('2019-05-20 00:00:00'): 82,
             Timestamp('2019-05-13 00:00:00'): 86,
             Timestamp('2019-05-06 00:00:00'): 93,
             Timestamp('2019-04-29 00:00:00'): 72,
             Timestamp('2019-04-22 00:00:00'): 86,
             Timestamp('2019-04-15 00:00:00'): 93,
             Timestamp('2019-04-08 00:00:00'): 85,
             Timestamp('2019-04-01 00:00:00'): 54,
             Timestamp('2019-03-25 00:00:00'): 81,
             Timestamp('2019-03-18 00:00:00'): 86,
             Timestamp('2019-03-11 00:00:00'): 76,
             Timestamp('2019-03-04 00:00:00'): 108,
             Timestamp('2019-02-25 00:00:00'): 54,
             Timestamp('2019-02-18 00:00:00'): 76,
             Timestamp('2019-02-11 00:00:00'): 86,
             Timestamp('2019-02-04 00:00:00'): 90,
             Timestamp('2019-01-28 00:00:00'): 68,
             Timestamp('2019-01-21 00:00:00'): 66,
             Timestamp('2019-01-14 00:00:00'): 83,
             Timestamp('2019-01-07 00:00:00'): 48,
             Timestamp('2018-12-31 00:00:00'): 93,
             Timestamp('2018-12-24 00:00:00'): 69,
             Timestamp('2018-12-17 00:00:00'): 87,
             Timestamp('2018-12-10 00:00:00'): 46,
             Timestamp('2018-12-03 00:00:00'): 74,
             Timestamp('2018-11-26 00:00:00'): 91,
             Timestamp('2018-11-19 00:00:00'): 38,
             Timestamp('2018-11-12 00:00:00'): 72,
             Timestamp('2018-11-05 00:00:00'): 44,
             Timestamp('2018-10-29 00:00:00'): 59,
             Timestamp('2018-10-22 00:00:00'): 107,
             Timestamp('2018-10-15 00:00:00'): 106,
             Timestamp('2018-10-08 00:00:00'): 95,
             Timestamp('2018-10-01 00:00:00'): 75,
             Timestamp('2018-09-24 00:00:00'): 102,
             Timestamp('2018-09-17 00:00:00'): 88,
             Timestamp('2018-09-10 00:00:00'): 89,
             Timestamp('2018-09-03 00:00:00'): 85,
             Timestamp('2018-08-27 00:00:00'): 58,
             Timestamp('2018-08-20 00:00:00'): 66,
             Timestamp('2018-08-13 00:00:00'): 93,
             Timestamp('2018-08-06 00:00:00'): 97,
             Timestamp('2018-07-30 00:00:00'): 81,
             Timestamp('2018-07-23 00:00:00'): 74,
             Timestamp('2018-07-16 00:00:00'): 72,
             Timestamp('2018-07-09 00:00:00'): 73,
             Timestamp('2018-07-02 00:00:00'): 35,
             Timestamp('2018-06-25 00:00:00'): 97,
             Timestamp('2018-06-18 00:00:00'): 95,
             Timestamp('2018-06-11 00:00:00'): 62,
             Timestamp('2018-06-04 00:00:00'): 59,
             Timestamp('2018-05-28 00:00:00'): 47,
             Timestamp('2018-05-21 00:00:00'): 64,
             Timestamp('2018-05-14 00:00:00'): 48,
             Timestamp('2018-05-07 00:00:00'): 68,
             Timestamp('2018-04-30 00:00:00'): 47,
             Timestamp('2018-04-23 00:00:00'): 35,
             Timestamp('2018-04-16 00:00:00'): 26,
             Timestamp('2018-04-09 00:00:00'): 34,
             Timestamp('2018-04-02 00:00:00'): 56,
             Timestamp('2018-03-26 00:00:00'): 43,
             Timestamp('2018-03-19 00:00:00'): 74,
             Timestamp('2018-03-12 00:00:00'): 22,
             Timestamp('2018-03-05 00:00:00'): 46,
             Timestamp('2018-02-26 00:00:00'): 42,
             Timestamp('2018-02-19 00:00:00'): 18,
             Timestamp('2018-02-12 00:00:00'): 43,
             Timestamp('2018-02-05 00:00:00'): 82,
             Timestamp('2018-01-29 00:00:00'): 64,
             Timestamp('2018-01-22 00:00:00'): 43,
             Timestamp('2018-01-15 00:00:00'): 10,
             Timestamp('2018-01-08 00:00:00'): 30,
             Timestamp('2018-01-01 00:00:00'): 28,
             Timestamp('2017-12-25 00:00:00'): 15,
             Timestamp('2017-12-18 00:00:00'): 20,
             Timestamp('2017-12-11 00:00:00'): 16,
             Timestamp('2017-12-04 00:00:00'): 31,
             Timestamp('2017-11-27 00:00:00'): 11,
             Timestamp('2017-11-20 00:00:00'): 28,
             Timestamp('2017-11-13 00:00:00'): 28,
             Timestamp('2017-11-06 00:00:00'): 19,
             Timestamp('2017-10-30 00:00:00'): 35,
             Timestamp('2017-10-23 00:00:00'): 32,
             Timestamp('2017-10-16 00:00:00'): 45,
             Timestamp('2017-10-09 00:00:00'): 28,
             Timestamp('2017-10-02 00:00:00'): 50,
             Timestamp('2017-09-25 00:00:00'): 58,
             Timestamp('2017-09-18 00:00:00'): 31,
             Timestamp('2017-09-11 00:00:00'): 47,
             Timestamp('2017-09-04 00:00:00'): 18,
             Timestamp('2017-08-28 00:00:00'): 16,
             Timestamp('2017-08-21 00:00:00'): 22,
             Timestamp('2017-08-14 00:00:00'): 22,
             Timestamp('2017-08-07 00:00:00'): 27,
             Timestamp('2017-07-31 00:00:00'): 29,
             Timestamp('2017-07-24 00:00:00'): 37,
             Timestamp('2017-07-17 00:00:00'): 24,
             Timestamp('2017-07-10 00:00:00'): 49,
             Timestamp('2017-07-03 00:00:00'): 21,
             Timestamp('2017-06-26 00:00:00'): 38,
             Timestamp('2017-06-19 00:00:00'): 44,
             Timestamp('2017-06-12 00:00:00'): 30,
             Timestamp('2017-06-05 00:00:00'): 44,
             Timestamp('2017-05-29 00:00:00'): 12,
             Timestamp('2017-05-22 00:00:00'): 22,
             Timestamp('2017-05-15 00:00:00'): 53,
             Timestamp('2017-05-08 00:00:00'): 35,
             Timestamp('2017-05-01 00:00:00'): 37,
             Timestamp('2017-04-24 00:00:00'): 36,
             Timestamp('2017-04-17 00:00:00'): 23,
             Timestamp('2017-04-10 00:00:00'): 27,
             Timestamp('2017-04-03 00:00:00'): 44,
             Timestamp('2017-03-27 00:00:00'): 43,
             Timestamp('2017-03-20 00:00:00'): 80,
             Timestamp('2017-03-13 00:00:00'): 61,
             Timestamp('2017-03-06 00:00:00'): 60,
             Timestamp('2017-02-27 00:00:00'): 66,
             Timestamp('2017-02-20 00:00:00'): 49,
             Timestamp('2017-02-13 00:00:00'): 53,
             Timestamp('2017-02-06 00:00:00'): 36,
             Timestamp('2017-01-30 00:00:00'): 44,
             Timestamp('2017-01-23 00:00:00'): 63,
             Timestamp('2017-01-16 00:00:00'): 79,
             Timestamp('2017-01-09 00:00:00'): 72,
             Timestamp('2017-01-02 00:00:00'): 24,
             Timestamp('2016-12-26 00:00:00'): 14,
             Timestamp('2016-12-19 00:00:00'): 29,
             Timestamp('2016-12-12 00:00:00'): 18,
             Timestamp('2016-12-05 00:00:00'): 7,
             Timestamp('2016-11-28 00:00:00'): 38,
             Timestamp('2016-11-21 00:00:00'): 35,
             Timestamp('2016-11-14 00:00:00'): 45,
             Timestamp('2016-11-07 00:00:00'): 34,
             Timestamp('2016-10-31 00:00:00'): 41,
             Timestamp('2016-10-24 00:00:00'): 36,
             Timestamp('2016-10-17 00:00:00'): 48,
             Timestamp('2016-10-10 00:00:00'): 36,
             Timestamp('2016-10-03 00:00:00'): 34,
             Timestamp('2016-09-26 00:00:00'): 43,
             Timestamp('2016-09-19 00:00:00'): 44,
             Timestamp('2016-09-12 00:00:00'): 69,
             Timestamp('2016-09-05 00:00:00'): 43,
             Timestamp('2016-08-29 00:00:00'): 51,
             Timestamp('2016-08-22 00:00:00'): 58,
             Timestamp('2016-08-15 00:00:00'): 59,
             Timestamp('2016-08-08 00:00:00'): 35,
             Timestamp('2016-08-01 00:00:00'): 37,
             Timestamp('2016-07-25 00:00:00'): 62,
             Timestamp('2016-07-18 00:00:00'): 47,
             Timestamp('2016-07-11 00:00:00'): 51,
             Timestamp('2016-07-04 00:00:00'): 62,
             Timestamp('2016-06-27 00:00:00'): 67,
             Timestamp('2016-06-20 00:00:00'): 67,
             Timestamp('2016-06-13 00:00:00'): 34,
             Timestamp('2016-06-06 00:00:00'): 51,
             Timestamp('2016-05-30 00:00:00'): 37,
             Timestamp('2016-05-23 00:00:00'): 42,
             Timestamp('2016-05-16 00:00:00'): 50,
             Timestamp('2016-05-09 00:00:00'): 38,
             Timestamp('2016-05-02 00:00:00'): 37,
             Timestamp('2016-04-25 00:00:00'): 44,
             Timestamp('2016-04-18 00:00:00'): 51,
             Timestamp('2016-04-11 00:00:00'): 59,
             Timestamp('2016-04-04 00:00:00'): 49,
             Timestamp('2016-03-28 00:00:00'): 74,
             Timestamp('2016-03-21 00:00:00'): 37,
             Timestamp('2016-03-14 00:00:00'): 44,
             Timestamp('2016-03-07 00:00:00'): 28,
             Timestamp('2016-02-29 00:00:00'): 38,
             Timestamp('2016-02-22 00:00:00'): 39,
             Timestamp('2016-02-15 00:00:00'): 21,
             Timestamp('2016-02-08 00:00:00'): 45,
             Timestamp('2016-02-01 00:00:00'): 28,
             Timestamp('2016-01-25 00:00:00'): 37,
             Timestamp('2016-01-18 00:00:00'): 55,
             Timestamp('2016-01-11 00:00:00'): 48,
             Timestamp('2016-01-04 00:00:00'): 39,
             Timestamp('2015-12-28 00:00:00'): 12})

In [ ]:
# Count frequencies of economic keywords by day
countbyday=defaultdict(int)
for index,row in WSB_reddits.iterrows():
    for word in range(len(row['text'].split(' '))-1):
        words = row['text'].split(' ')
        if f'{words[word]} {words[word +1]}' in trade_matchers:
            countbyday[row['day']] += 1
#     break
countbyday

In [ ]:
# Create a dataframe of the frequency counts of economic keywords by week
wsb_weekdf = pd.DataFrame([countbyweek]).transpose().reset_index()
wsb_weekdf.columns=(['Week','Count'])
wsb_weekdf

In [46]:
# Save the dataframe in a csv file for uses as a possible feature in predictive machine learning models 
wsb_weekdf.to_csv('./Data/wsb_weekdf_count.csv', index=False)

In [47]:
# Create a dataframe of the frequency counts of economic keywords by day
wsb_daydf = pd.DataFrame([countbyday]).transpose().reset_index()
wsb_daydf.columns=(['Date','Count'])
wsb_daydf

           Date  Count
0    2016-01-01      7
1    2016-01-02      1
2    2016-01-03     74
3    2016-01-04     22
4    2016-01-05     13
...         ...    ...
1916 2021-04-27    731
1917 2021-04-28    699
1918 2021-04-29    512
1919 2021-04-30    829
1920 2021-05-01      8

[1921 rows x 2 columns]

In [48]:
# Save the dataframe in a csv file for uses as a possible feature in predictive machine learning models 
wsb_daydf.to_csv('./Data/wsb_daydf_count.csv', index=False)

In [175]:
wsb_daydf = pd.DataFrame([countbyday]).transpose().reset_index()
wsb_daydf.columns=(['Date','Count'])
wsb_daydf

           Date  Count
0    2016-01-01      7
1    2016-01-03     28
2    2016-01-04      8
3    2016-01-05      5
4    2016-01-06     17
...         ...    ...
1903 2021-04-27    214
1904 2021-04-28    184
1905 2021-04-29    153
1906 2021-04-30    197
1907 2021-05-01      5

[1908 rows x 2 columns]

In [177]:
wsb_daydf.to_csv('./Data/wsb_daydf_count.csv', index=False)

In [195]:
# Introduce negative financial keywords
Negative = ['abandon', 'abandoned', 'abandoning', 'abandonment', 'abandonments', 'abandons', 'abdicated',
                       'abdicates', 'abdicating', 'abdication', 'abdications', 'aberrant', 'aberration', 'aberrational',
                       'aberrations', 'abetting', 'abnormal', 'abnormalities', 'abnormality', 'abnormally', 'abolish',
                       'abolished', 'abolishes', 'abolishing', 'abrogate', 'abrogated', 'abrogates', 'abrogating',
                       'abrogation', 'abrogations', 'abrupt', 'abruptly', 'abruptness', 'absence', 'absences',
                       'absenteeism', 'abuse', 'abused', 'abuses', 'abusing', 'abusive', 'abusively', 'abusiveness',
                       'accident', 'accidental', 'accidentally', 'accidents', 'accusation', 'accusations', 'accuse',
                       'accused', 'accuses', 'accusing', 'acquiesce', 'acquiesced', 'acquiesces', 'acquiescing',
                       'acquit', 'acquits', 'acquittal', 'acquittals', 'acquitted', 'acquitting', 'adulterate',
                       'adulterated', 'adulterating', 'adulteration', 'adulterations', 'adversarial', 'adversaries',
                       'adversary', 'adverse', 'adversely', 'adversities', 'adversity', 'aftermath', 'aftermaths',
                       'against', 'aggravate', 'aggravated', 'aggravates', 'aggravating', 'aggravation', 'aggravations',
                       'alerted', 'alerting', 'alienate', 'alienated', 'alienates', 'alienating', 'alienation',
                       'alienations', 'allegation', 'allegations', 'allege', 'alleged', 'allegedly', 'alleges',
                       'alleging', 'annoy', 'annoyance', 'annoyances', 'annoyed', 'annoying', 'annoys', 'annul',
                       'annulled', 'annulling', 'annulment', 'annulments', 'annuls', 'anomalies', 'anomalous',
                       'anomalously', 'anomaly', 'anticompetitive', 'antitrust', 'argue', 'argued', 'arguing',
                       'argument', 'argumentative', 'arguments', 'arrearage', 'arrearages', 'arrears', 'arrest',
                       'arrested', 'arrests', 'artificially', 'assault', 'assaulted', 'assaulting', 'assaults',
                       'assertions', 'attrition', 'aversely', 'backdating', 'bad', 'bail', 'bailout', 'balk', 'balked',
                       'bankrupt', 'bankruptcies', 'bankruptcy', 'bankrupted', 'bankrupting', 'bankrupts', 'bans',
                       'barred', 'barrier', 'barriers', 'bottleneck', 'bottlenecks', 'boycott', 'boycotted',
                       'boycotting', 'boycotts', 'breach', 'breached', 'breaches', 'breaching', 'break', 'breakage',
                       'breakages', 'breakdown', 'breakdowns', 'breaking', 'breaks', 'bribe', 'bribed', 'briberies',
                       'bribery', 'bribes', 'bribing', 'bridge', 'broken', 'burden', 'burdened', 'burdening', 'burdens',
                       'burdensome', 'burned', 'calamities', 'calamitous', 'calamity', 'cancel', 'canceled',
                       'canceling', 'cancellation', 'cancellations', 'cancelled', 'cancelling', 'cancels', 'careless',
                       'carelessly', 'carelessness', 'catastrophe', 'catastrophes', 'catastrophic', 'catastrophically',
                       'caution', 'cautionary', 'cautioned', 'cautioning', 'cautions', 'cease', 'ceased', 'ceases',
                       'ceasing', 'censure', 'censured', 'censures', 'censuring', 'challenge', 'challenged',
                       'challenges', 'challenging', 'chargeoffs', 'circumvent', 'circumvented', 'circumventing',
                       'circumvention', 'circumventions', 'circumvents', 'claiming', 'claims', 'clawback', 'closed',
                       'closeout', 'closeouts', 'closing', 'closings', 'closure', 'closures', 'coerce', 'coerced',
                       'coerces', 'coercing', 'coercion', 'coercive', 'collapse', 'collapsed', 'collapses',
                       'collapsing', 'collision', 'collisions', 'collude', 'colluded', 'colludes', 'colluding',
                       'collusion', 'collusions', 'collusive', 'complain', 'complained', 'complaining', 'complains',
                       'complaint', 'complaints', 'complicate', 'complicated', 'complicates', 'complicating',
                       'complication', 'complications', 'compulsion', 'concealed', 'concealing', 'concede', 'conceded',
                       'concedes', 'conceding', 'concern', 'concerned', 'concerns', 'conciliating', 'conciliation',
                       'conciliations', 'condemn', 'condemnation', 'condemnations', 'condemned', 'condemning',
                       'condemns', 'condone', 'condoned', 'confess', 'confessed', 'confesses', 'confessing',
                       'confession', 'confine', 'confined', 'confinement', 'confinements', 'confines', 'confining',
                       'confiscate', 'confiscated', 'confiscates', 'confiscating', 'confiscation', 'confiscations',
                       'conflict', 'conflicted', 'conflicting', 'conflicts', 'confront', 'confrontation',
                       'confrontational', 'confrontations', 'confronted', 'confronting', 'confronts', 'confuse',
                       'confused', 'confuses', 'confusing', 'confusingly', 'confusion', 'conspiracies', 'conspiracy',
                       'conspirator', 'conspiratorial', 'conspirators', 'conspire', 'conspired', 'conspires',
                       'conspiring', 'contempt', 'contend', 'contended', 'contending', 'contends', 'contention',
                       'contentions', 'contentious', 'contentiously', 'contested', 'contesting', 'contraction',
                       'contractions', 'contradict', 'contradicted', 'contradicting', 'contradiction', 'contradictions',
                       'contradictory', 'contradicts', 'contrary', 'controversial', 'controversies', 'controversy',
                       'convict', 'convicted', 'convicting', 'conviction', 'convictions', 'corrected', 'correcting',
                       'correction', 'corrections', 'corrects', 'corrupt', 'corrupted', 'corrupting', 'corruption',
                       'corruptions', 'corruptly', 'corruptness', 'costly', 'counterclaim', 'counterclaimed',
                       'counterclaiming', 'counterclaims', 'counterfeit', 'counterfeited', 'counterfeiter',
                       'counterfeiters', 'counterfeiting', 'counterfeits', 'countermeasure', 'countermeasures', 'crime',
                       'crimes', 'criminal', 'criminally', 'criminals', 'crises', 'crisis', 'critical', 'critically',
                       'criticism', 'criticisms', 'criticize', 'criticized', 'criticizes', 'criticizing', 'crucial',
                       'crucially', 'culpability', 'culpable', 'culpably', 'cumbersome', 'curtail', 'curtailed',
                       'curtailing', 'curtailment', 'curtailments', 'curtails', 'cut', 'cutback', 'cutbacks',
                       'cyberattack', 'cyberattacks', 'cyberbullying', 'cybercrime', 'cybercrimes', 'cybercriminal',
                       'cybercriminals', 'damage', 'damaged', 'damages', 'damaging', 'dampen', 'dampened', 'danger',
                       'dangerous', 'dangerously', 'dangers', 'deadlock', 'deadlocked', 'deadlocking', 'deadlocks',
                       'deadweight', 'deadweights', 'debarment', 'debarments', 'debarred', 'deceased', 'deceit',
                       'deceitful', 'deceitfulness', 'deceive', 'deceived', 'deceives', 'deceiving', 'deception',
                       'deceptions', 'deceptive', 'deceptively', 'decline', 'declined', 'declines', 'declining',
                       'deface', 'defaced', 'defacement', 'defamation', 'defamations', 'defamatory', 'defame',
                       'defamed', 'defames', 'defaming', 'default', 'defaulted', 'defaulting', 'defaults', 'defeat',
                       'defeated', 'defeating', 'defeats', 'defect', 'defective', 'defects', 'defend', 'defendant',
                       'defendants', 'defended', 'defending', 'defends', 'defensive', 'defer', 'deficiencies',
                       'deficiency', 'deficient', 'deficit', 'deficits', 'defraud', 'defrauded', 'defrauding',
                       'defrauds', 'defunct', 'degradation', 'degradations', 'degrade', 'degraded', 'degrades',
                       'degrading', 'delay', 'delayed', 'delaying', 'delays', 'deleterious', 'deliberate',
                       'deliberated', 'deliberately', 'delinquencies', 'delinquency', 'delinquent', 'delinquently',
                       'delinquents', 'delist', 'delisted', 'delisting', 'delists', 'demise', 'demised', 'demises',
                       'demising', 'demolish', 'demolished', 'demolishes', 'demolishing', 'demolition', 'demolitions',
                       'demote', 'demoted', 'demotes', 'demoting', 'demotion', 'demotions', 'denial', 'denials',
                       'denied', 'denies', 'denigrate', 'denigrated', 'denigrates', 'denigrating', 'denigration',
                       'deny', 'denying', 'deplete', 'depleted', 'depletes', 'depleting', 'depletion', 'depletions',
                       'deprecation', 'depress', 'depressed', 'depresses', 'depressing', 'deprivation', 'deprive',
                       'deprived', 'deprives', 'depriving', 'derelict', 'dereliction', 'derogatory', 'destabilization',
                       'destabilize', 'destabilized', 'destabilizing', 'destroy', 'destroyed', 'destroying', 'destroys',
                       'destruction', 'destructive', 'detain', 'detained', 'detention', 'detentions', 'deter',
                       'deteriorate', 'deteriorated', 'deteriorates', 'deteriorating', 'deterioration',
                       'deteriorations', 'deterred', 'deterrence', 'deterrences', 'deterrent', 'deterrents',
                       'deterring', 'deters', 'detract', 'detracted', 'detracting', 'detriment', 'detrimental',
                       'detrimentally', 'detriments', 'devalue', 'devalued', 'devalues', 'devaluing', 'devastate',
                       'devastated', 'devastating', 'devastation', 'deviate', 'deviated', 'deviates', 'deviating',
                       'deviation', 'deviations', 'devolve', 'devolved', 'devolves', 'devolving', 'difficult',
                       'difficulties', 'difficultly', 'difficulty', 'diminish', 'diminished', 'diminishes',
                       'diminishing', 'diminution', 'disadvantage', 'disadvantaged', 'disadvantageous', 'disadvantages',
                       'disaffiliation', 'disagree', 'disagreeable', 'disagreed', 'disagreeing', 'disagreement',
                       'disagreements', 'disagrees', 'disallow', 'disallowance', 'disallowances', 'disallowed',
                       'disallowing', 'disallows', 'disappear', 'disappearance', 'disappearances', 'disappeared',
                       'disappearing', 'disappears', 'disappoint', 'disappointed', 'disappointing', 'disappointingly',
                       'disappointment', 'disappointments', 'disappoints', 'disapproval', 'disapprovals', 'disapprove',
                       'disapproved', 'disapproves', 'disapproving', 'disassociates', 'disassociating',
                       'disassociation', 'disassociations', 'disaster', 'disasters', 'disastrous', 'disastrously',
                       'disavow', 'disavowal', 'disavowed', 'disavowing', 'disavows', 'disciplinary', 'disclaim',
                       'disclaimed', 'disclaimer', 'disclaimers', 'disclaiming', 'disclaims', 'disclose', 'disclosed',
                       'discloses', 'disclosing', 'discontinuance', 'discontinuances', 'discontinuation',
                       'discontinuations', 'discontinue', 'discontinued', 'discontinues', 'discontinuing', 'discourage',
                       'discouraged', 'discourages', 'discouraging', 'discredit', 'discredited', 'discrediting',
                       'discredits', 'discrepancies', 'discrepancy', 'disfavor', 'disfavored', 'disfavoring',
                       'disfavors', 'disgorge', 'disgorged', 'disgorgement', 'disgorgements', 'disgorges', 'disgorging',
                       'disgrace', 'disgraceful', 'disgracefully', 'dishonest', 'dishonestly', 'dishonesty', 'dishonor',
                       'dishonorable', 'dishonorably', 'dishonored', 'dishonoring', 'dishonors', 'disincentives',
                       'disinterested', 'disinterestedly', 'disinterestedness', 'disloyal', 'disloyally', 'disloyalty',
                       'dismal', 'dismally', 'dismiss', 'dismissal', 'dismissals', 'dismissed', 'dismisses',
                       'dismissing', 'disorderly', 'disparage', 'disparaged', 'disparagement', 'disparagements',
                       'disparages', 'disparaging', 'disparagingly', 'disparities', 'disparity', 'displace',
                       'displaced', 'displacement', 'displacements', 'displaces', 'displacing', 'dispose', 'dispossess',
                       'dispossessed', 'dispossesses', 'dispossessing', 'disproportion', 'disproportional',
                       'disproportionate', 'disproportionately', 'dispute', 'disputed', 'disputes', 'disputing',
                       'disqualification', 'disqualifications', 'disqualified', 'disqualifies', 'disqualify',
                       'disqualifying', 'disregard', 'disregarded', 'disregarding', 'disregards', 'disreputable',
                       'disrepute', 'disrupt', 'disrupted', 'disrupting', 'disruption', 'disruptions', 'disruptive',
                       'disrupts', 'dissatisfaction', 'dissatisfied', 'dissent', 'dissented', 'dissenter', 'dissenters',
                       'dissenting', 'dissents', 'dissident', 'dissidents', 'dissolution', 'dissolutions', 'distort',
                       'distorted', 'distorting', 'distortion', 'distortions', 'distorts', 'distract', 'distracted',
                       'distracting', 'distraction', 'distractions', 'distracts', 'distress', 'distressed', 'disturb',
                       'disturbance', 'disturbances', 'disturbed', 'disturbing', 'disturbs', 'diversion', 'divert',
                       'diverted', 'diverting', 'diverts', 'divest', 'divested', 'divesting', 'divestiture',
                       'divestitures', 'divestment', 'divestments', 'divests', 'divorce', 'divorced', 'divulge',
                       'divulged', 'divulges', 'divulging', 'doubt', 'doubted', 'doubtful', 'doubts', 'downgrade',
                       'downgraded', 'downgrades', 'downgrading', 'downsize', 'downsized', 'downsizes', 'downsizing',
                       'downsizings', 'downtime', 'downtimes', 'downturn', 'downturns', 'downward', 'downwards', 'drag',
                       'drastic', 'drastically', 'drawback', 'drawbacks', 'dropped', 'drought', 'droughts', 'duress',
                       'dysfunction', 'dysfunctional', 'dysfunctions', 'easing', 'egregious', 'egregiously', 'embargo',
                       'embargoed', 'embargoes', 'embargoing', 'embarrass', 'embarrassed', 'embarrasses',
                       'embarrassing', 'embarrassment', 'embarrassments', 'embezzle', 'embezzled', 'embezzlement',
                       'embezzlements', 'embezzler', 'embezzles', 'embezzling', 'encroach', 'encroached', 'encroaches',
                       'encroaching', 'encroachment', 'encroachments', 'encumber', 'encumbered', 'encumbering',
                       'encumbers', 'encumbrance', 'encumbrances', 'endanger', 'endangered', 'endangering',
                       'endangerment', 'endangers', 'enjoin', 'enjoined', 'enjoining', 'enjoins', 'erode', 'eroded',
                       'erodes', 'eroding', 'erosion', 'erratic', 'erratically', 'erred', 'erring', 'erroneous',
                       'erroneously', 'error', 'errors', 'errs', 'escalate', 'escalated', 'escalates', 'escalating',
                       'evade', 'evaded', 'evades', 'evading', 'evasion', 'evasions', 'evasive', 'evict', 'evicted',
                       'evicting', 'eviction', 'evictions', 'evicts', 'exacerbate', 'exacerbated', 'exacerbates',
                       'exacerbating', 'exacerbation', 'exacerbations', 'exaggerate', 'exaggerated', 'exaggerates',
                       'exaggerating', 'exaggeration', 'excessive', 'excessively', 'exculpate', 'exculpated',
                       'exculpates', 'exculpating', 'exculpation', 'exculpations', 'exculpatory', 'exonerate',
                       'exonerated', 'exonerates', 'exonerating', 'exoneration', 'exonerations', 'exploit',
                       'exploitation', 'exploitations', 'exploitative', 'exploited', 'exploiting', 'exploits', 'expose',
                       'exposed', 'exposes', 'exposing', 'expropriate', 'expropriated', 'expropriates', 'expropriating',
                       'expropriation', 'expropriations', 'expulsion', 'expulsions', 'extenuating', 'fail', 'failed',
                       'failing', 'failings', 'fails', 'failure', 'failures', 'fallout', 'false', 'falsely',
                       'falsification', 'falsifications', 'falsified', 'falsifies', 'falsify', 'falsifying', 'falsity',
                       'fatalities', 'fatality', 'fatally', 'fault', 'faulted', 'faults', 'faulty', 'fear', 'fears',
                       'felonies', 'felonious', 'felony', 'fictitious', 'fined', 'fines', 'fired', 'firing', 'flaw',
                       'flawed', 'flaws', 'forbid', 'forbidden', 'forbidding', 'forbids', 'force', 'forced', 'forcing',
                       'foreclose', 'foreclosed', 'forecloses', 'foreclosing', 'foreclosure', 'foreclosures', 'forego',
                       'foregoes', 'foregone', 'forestall', 'forestalled', 'forestalling', 'forestalls', 'forfeit',
                       'forfeited', 'forfeiting', 'forfeits', 'forfeiture', 'forfeitures', 'forgers', 'forgery',
                       'fraud', 'frauds', 'fraudulence', 'fraudulent', 'fraudulently', 'frivolous', 'frivolously',
                       'frustrate', 'frustrated', 'frustrates', 'frustrating', 'frustratingly', 'frustration',
                       'frustrations', 'fugitive', 'fugitives', 'gratuitous', 'gratuitously', 'grievance', 'grievances',
                       'grossly', 'groundless', 'guilty', 'halt', 'halted', 'hamper', 'hampered', 'hampering',
                       'hampers', 'harass', 'harassed', 'harassing', 'harassment', 'hardship', 'hardships', 'harm',
                       'harmed', 'harmful', 'harmfully', 'harming', 'harms', 'harsh', 'harsher', 'harshest', 'harshly',
                       'harshness', 'hazard', 'hazardous', 'hazards', 'hinder', 'hindered', 'hindering', 'hinders',
                       'hindrance', 'hindrances', 'hostile', 'hostility', 'hurt', 'hurting', 'idle', 'idled', 'idling',
                       'ignore', 'ignored', 'ignores', 'ignoring', 'ill', 'illegal', 'illegalities', 'illegality',
                       'illegally', 'illegible', 'illicit', 'illicitly', 'illiquid', 'illiquidity', 'imbalance',
                       'imbalances', 'immature', 'immoral', 'impair', 'impaired', 'impairing', 'impairment',
                       'impairments', 'impairs', 'impasse', 'impasses', 'impede', 'impeded', 'impedes', 'impediment',
                       'impediments', 'impeding', 'impending', 'imperative', 'imperfection', 'imperfections', 'imperil',
                       'impermissible', 'implicate', 'implicated', 'implicates', 'implicating', 'impossibility',
                       'impossible', 'impound', 'impounded', 'impounding', 'impounds', 'impracticable', 'impractical',
                       'impracticalities', 'impracticality', 'imprisonment', 'improper', 'improperly', 'improprieties',
                       'impropriety', 'imprudent', 'imprudently', 'inability', 'inaccessible', 'inaccuracies',
                       'inaccuracy', 'inaccurate', 'inaccurately', 'inaction', 'inactions', 'inactivate', 'inactivated',
                       'inactivates', 'inactivating', 'inactivation', 'inactivations', 'inactivity', 'inadequacies',
                       'inadequacy', 'inadequate', 'inadequately', 'inadvertent', 'inadvertently', 'inadvisability',
                       'inadvisable', 'inappropriate', 'inappropriately', 'inattention', 'incapable', 'incapacitated',
                       'incapacity', 'incarcerate', 'incarcerated', 'incarcerates', 'incarcerating', 'incarceration',
                       'incarcerations', 'incidence', 'incidences', 'incident', 'incidents', 'incompatibilities',
                       'incompatibility', 'incompatible', 'incompetence', 'incompetency', 'incompetent',
                       'incompetently', 'incompetents', 'incomplete', 'incompletely', 'incompleteness', 'inconclusive',
                       'inconsistencies', 'inconsistency', 'inconsistent', 'inconsistently', 'inconvenience',
                       'inconveniences', 'inconvenient', 'incorrect', 'incorrectly', 'incorrectness', 'indecency',
                       'indecent', 'indefeasible', 'indefeasibly', 'indict', 'indictable', 'indicted', 'indicting',
                       'indictment', 'indictments', 'ineffective', 'ineffectively', 'ineffectiveness', 'inefficiencies',
                       'inefficiency', 'inefficient', 'inefficiently', 'ineligibility', 'ineligible', 'inequitable',
                       'inequitably', 'inequities', 'inequity', 'inevitable', 'inexperience', 'inexperienced',
                       'inferior', 'inflicted', 'infraction', 'infractions', 'infringe', 'infringed', 'infringement',
                       'infringements', 'infringes', 'infringing', 'inhibited', 'inimical', 'injunction', 'injunctions',
                       'injure', 'injured', 'injures', 'injuries', 'injuring', 'injurious', 'injury', 'inordinate',
                       'inordinately', 'inquiry', 'insecure', 'insensitive', 'insolvencies', 'insolvency', 'insolvent',
                       'instability', 'insubordination', 'insufficiency', 'insufficient', 'insufficiently',
                       'insurrection', 'insurrections', 'intentional', 'interfere', 'interfered', 'interference',
                       'interferences', 'interferes', 'interfering', 'intermittent', 'intermittently', 'interrupt',
                       'interrupted', 'interrupting', 'interruption', 'interruptions', 'interrupts', 'intimidation',
                       'intrusion', 'invalid', 'invalidate', 'invalidated', 'invalidates', 'invalidating',
                       'invalidation', 'invalidity', 'investigate', 'investigated', 'investigates', 'investigating',
                       'investigation', 'investigations', 'involuntarily', 'involuntary', 'irreconcilable',
                       'irreconcilably', 'irrecoverable', 'irrecoverably', 'irregular', 'irregularities',
                       'irregularity', 'irregularly', 'irreparable', 'irreparably', 'irreversible', 'jeopardize',
                       'jeopardized', 'justifiable', 'kickback', 'kickbacks', 'knowingly', 'lack', 'lacked', 'lacking',
                       'lackluster', 'lacks', 'lag', 'lagged', 'lagging', 'lags', 'lapse', 'lapsed', 'lapses',
                       'lapsing', 'late', 'laundering', 'layoff', 'layoffs', 'lie', 'limitation', 'limitations',
                       'lingering', 'liquidate', 'liquidated', 'liquidates', 'liquidating', 'liquidation',
                       'liquidations', 'liquidator', 'liquidators', 'litigant', 'litigants', 'litigate', 'litigated',
                       'litigates', 'litigating', 'litigation', 'litigations', 'lockout', 'lockouts', 'lose', 'loses',
                       'losing', 'loss', 'losses', 'lost', 'lying', 'malfeasance', 'malfunction', 'malfunctioned',
                       'malfunctioning', 'malfunctions', 'malice', 'malicious', 'maliciously', 'malpractice',
                       'manipulate', 'manipulated', 'manipulates', 'manipulating', 'manipulation', 'manipulations',
                       'manipulative', 'markdown', 'markdowns', 'misapplication', 'misapplications', 'misapplied',
                       'misapplies', 'misapply', 'misapplying', 'misappropriate', 'misappropriated', 'misappropriates',
                       'misappropriating', 'misappropriation', 'misappropriations', 'misbranded', 'miscalculate',
                       'miscalculated', 'miscalculates', 'miscalculating', 'miscalculation', 'miscalculations',
                       'mischaracterization', 'mischief', 'misclassification', 'misclassifications', 'misclassified',
                       'misclassify', 'miscommunication', 'misconduct', 'misdated', 'misdemeanor', 'misdemeanors',
                       'misdirected', 'mishandle', 'mishandled', 'mishandles', 'mishandling', 'misinform',
                       'misinformation', 'misinformed', 'misinforming', 'misinforms', 'misinterpret',
                       'misinterpretation', 'misinterpretations', 'misinterpreted', 'misinterpreting', 'misinterprets',
                       'misjudge', 'misjudged', 'misjudges', 'misjudging', 'misjudgment', 'misjudgments', 'mislabel',
                       'mislabeled', 'mislabeling', 'mislabelled', 'mislabels', 'mislead', 'misleading', 'misleadingly',
                       'misleads', 'misled', 'mismanage', 'mismanaged', 'mismanagement', 'mismanages', 'mismanaging',
                       'mismatch', 'mismatched', 'mismatches', 'mismatching', 'misplaced', 'misprice', 'mispricing',
                       'mispricings', 'misrepresent', 'misrepresentation', 'misrepresentations', 'misrepresented',
                       'misrepresenting', 'misrepresents', 'miss', 'missed', 'misses', 'misstate', 'misstated',
                       'misstatement', 'misstatements', 'misstates', 'misstating', 'misstep', 'missteps', 'mistake',
                       'mistaken', 'mistakenly', 'mistakes', 'mistaking', 'mistrial', 'mistrials', 'misunderstand',
                       'misunderstanding', 'misunderstandings', 'misunderstood', 'misuse', 'misused', 'misuses',
                       'misusing', 'monopolistic', 'monopolists', 'monopolization', 'monopolize', 'monopolized',
                       'monopolizes', 'monopolizing', 'monopoly', 'moratoria', 'moratorium', 'moratoriums',
                       'mothballed', 'mothballing', 'negative', 'negatively', 'negatives', 'neglect', 'neglected',
                       'neglectful', 'neglecting', 'neglects', 'negligence', 'negligences', 'negligent', 'negligently',
                       'nonattainment', 'noncompetitive', 'noncompliance', 'noncompliances', 'noncompliant',
                       'noncomplying', 'nonconforming', 'nonconformities', 'nonconformity', 'nondisclosure',
                       'nonfunctional', 'nonpayment', 'nonpayments', 'nonperformance', 'nonperformances',
                       'nonperforming', 'nonproducing', 'nonproductive', 'nonrecoverable', 'nonrenewal', 'nuisance',
                       'nuisances', 'nullification', 'nullifications', 'nullified', 'nullifies', 'nullify',
                       'nullifying', 'objected', 'objecting', 'objection', 'objectionable', 'objectionably',
                       'objections', 'obscene', 'obscenity', 'obsolescence', 'obsolete', 'obstacle', 'obstacles',
                       'obstruct', 'obstructed', 'obstructing', 'obstruction', 'obstructions', 'offence', 'offences',
                       'offend', 'offended', 'offender', 'offenders', 'offending', 'offends', 'omission', 'omissions',
                       'omit', 'omits', 'omitted', 'omitting', 'onerous', 'opportunistic', 'opportunistically',
                       'oppose', 'opposed', 'opposes', 'opposing', 'opposition', 'oppositions', 'outage', 'outages',
                       'outdated', 'outmoded', 'overage', 'overages', 'overbuild', 'overbuilding', 'overbuilds',
                       'overbuilt', 'overburden', 'overburdened', 'overburdening', 'overcapacities', 'overcapacity',
                       'overcharge', 'overcharged', 'overcharges', 'overcharging', 'overcome', 'overcomes',
                       'overcoming', 'overdue', 'overestimate', 'overestimated', 'overestimates', 'overestimating',
                       'overestimation', 'overestimations', 'overload', 'overloaded', 'overloading', 'overloads',
                       'overlook', 'overlooked', 'overlooking', 'overlooks', 'overpaid', 'overpayment', 'overpayments',
                       'overproduced', 'overproduces', 'overproducing', 'overproduction', 'overrun', 'overrunning',
                       'overruns', 'overshadow', 'overshadowed', 'overshadowing', 'overshadows', 'overstate',
                       'overstated', 'overstatement', 'overstatements', 'overstates', 'overstating', 'oversupplied',
                       'oversupplies', 'oversupply', 'oversupplying', 'overtly', 'overturn', 'overturned',
                       'overturning', 'overturns', 'overvalue', 'overvalued', 'overvaluing', 'panic', 'panics',
                       'penalize', 'penalized', 'penalizes', 'penalizing', 'penalties', 'penalty', 'peril', 'perils',
                       'perjury', 'perpetrate', 'perpetrated', 'perpetrates', 'perpetrating', 'perpetration', 'persist',
                       'persisted', 'persistence', 'persistent', 'persistently', 'persisting', 'persists', 'pervasive',
                       'pervasively', 'pervasiveness', 'petty', 'picket', 'picketed', 'picketing', 'plaintiff',
                       'plaintiffs', 'plea', 'plead', 'pleaded', 'pleading', 'pleadings', 'pleads', 'pleas', 'pled',
                       'poor', 'poorly', 'poses', 'posing', 'postpone', 'postponed', 'postponement', 'postponements',
                       'postpones', 'postponing', 'precipitated', 'precipitous', 'precipitously', 'preclude',
                       'precluded', 'precludes', 'precluding', 'predatory', 'prejudice', 'prejudiced', 'prejudices',
                       'prejudicial', 'prejudicing', 'premature', 'prematurely', 'pressing', 'pretrial', 'preventing',
                       'prevention', 'prevents', 'problem', 'problematic', 'problematical', 'problems', 'prolong',
                       'prolongation', 'prolongations', 'prolonged', 'prolonging', 'prolongs', 'prone', 'prosecute',
                       'prosecuted', 'prosecutes', 'prosecuting', 'prosecution', 'prosecutions', 'protest', 'protested',
                       'protester', 'protesters', 'protesting', 'protestor', 'protestors', 'protests', 'protracted',
                       'protraction', 'provoke', 'provoked', 'provokes', 'provoking', 'punished', 'punishes',
                       'punishing', 'punishment', 'punishments', 'punitive', 'purport', 'purported', 'purportedly',
                       'purporting', 'purports', 'question', 'questionable', 'questionably', 'questioned',
                       'questioning', 'questions', 'quit', 'quitting', 'racketeer', 'racketeering', 'rationalization',
                       'rationalizations', 'rationalize', 'rationalized', 'rationalizes', 'rationalizing',
                       'reassessment', 'reassessments', 'reassign', 'reassigned', 'reassigning', 'reassignment',
                       'reassignments', 'reassigns', 'recall', 'recalled', 'recalling', 'recalls', 'recession',
                       'recessionary', 'recessions', 'reckless', 'recklessly', 'recklessness', 'redact', 'redacted',
                       'redacting', 'redaction', 'redactions', 'redefault', 'redefaulted', 'redefaults', 'redress',
                       'redressed', 'redresses', 'redressing', 'refusal', 'refusals', 'refuse', 'refused', 'refuses',
                       'refusing', 'reject', 'rejected', 'rejecting', 'rejection', 'rejections', 'rejects',
                       'relinquish', 'relinquished', 'relinquishes', 'relinquishing', 'relinquishment',
                       'relinquishments', 'reluctance', 'reluctant', 'renegotiate', 'renegotiated', 'renegotiates',
                       'renegotiating', 'renegotiation', 'renegotiations', 'renounce', 'renounced', 'renouncement',
                       'renouncements', 'renounces', 'renouncing', 'reparation', 'reparations', 'repossessed',
                       'repossesses', 'repossessing', 'repossession', 'repossessions', 'repudiate', 'repudiated',
                       'repudiates', 'repudiating', 'repudiation', 'repudiations', 'resign', 'resignation',
                       'resignations', 'resigned', 'resigning', 'resigns', 'restate', 'restated', 'restatement',
                       'restatements', 'restates', 'restating', 'restructure', 'restructured', 'restructures',
                       'restructuring', 'restructurings', 'retaliate', 'retaliated', 'retaliates', 'retaliating',
                       'retaliation', 'retaliations', 'retaliatory', 'retribution', 'retributions', 'revocation',
                       'revocations', 'revoke', 'revoked', 'revokes', 'revoking', 'ridicule', 'ridiculed', 'ridicules',
                       'ridiculing', 'riskier', 'riskiest', 'risky', 'sabotage', 'sacrifice', 'sacrificed',
                       'sacrifices', 'sacrificial', 'sacrificing', 'scandalous', 'scandals', 'scrutinize',
                       'scrutinized', 'scrutinizes', 'scrutinizing', 'scrutiny', 'secrecy', 'seize', 'seized', 'seizes',
                       'seizing', 'sentenced', 'sentencing', 'serious', 'seriously', 'seriousness', 'setback',
                       'setbacks', 'sever', 'severe', 'severed', 'severely', 'severities', 'severity', 'sharply',
                       'shocked', 'shortage', 'shortages', 'shortfall', 'shortfalls', 'shrinkage', 'shrinkages', 'shut',
                       'shutdown', 'shutdowns', 'shuts', 'shutting', 'slander', 'slandered', 'slanderous', 'slanders',
                       'slippage', 'slippages', 'slow', 'slowdown', 'slowdowns', 'slowed', 'slower', 'slowest',
                       'slowing', 'slowly', 'slowness', 'sluggish', 'sluggishly', 'sluggishness', 'solvencies',
                       'solvency', 'spam', 'spammers', 'spamming', 'staggering', 'stagnant', 'stagnate', 'stagnated',
                       'stagnates', 'stagnating', 'stagnation', 'standstill', 'standstills', 'stolen', 'stoppage',
                       'stoppages', 'stopped', 'stopping', 'stops', 'strain', 'strained', 'straining', 'strains',
                       'stress', 'stressed', 'stresses', 'stressful', 'stressing', 'stringent', 'subjected',
                       'subjecting', 'subjection', 'subpoena', 'subpoenaed', 'subpoenas', 'substandard', 'sue', 'sued',
                       'sues', 'suffer', 'suffered', 'suffering', 'suffers', 'suing', 'summoned', 'summoning',
                       'summons', 'summonses', 'susceptibility', 'susceptible', 'suspect', 'suspected', 'suspects',
                       'suspend', 'suspended', 'suspending', 'suspends', 'suspension', 'suspensions', 'suspicion',
                       'suspicions', 'suspicious', 'suspiciously', 'taint', 'tainted', 'tainting', 'taints', 'tampered',
                       'tense', 'terminate', 'terminated', 'terminates', 'terminating', 'termination', 'terminations',
                       'testify', 'testifying', 'threat', 'threaten', 'threatened', 'threatening', 'threatens',
                       'threats', 'tightening', 'tolerate', 'tolerated', 'tolerates', 'tolerating', 'toleration',
                       'tortuous', 'tortuously', 'tragedies', 'tragedy', 'tragic', 'tragically', 'traumatic', 'trouble',
                       'troubled', 'troubles', 'turbulence', 'turmoil', 'unable', 'unacceptable', 'unacceptably',
                       'unaccounted', 'unannounced', 'unanticipated', 'unapproved', 'unattractive', 'unauthorized',
                       'unavailability', 'unavailable', 'unavoidable', 'unavoidably', 'unaware', 'uncollectable',
                       'uncollected', 'uncollectibility', 'uncollectible', 'uncollectibles', 'uncompetitive',
                       'uncompleted', 'unconscionable', 'unconscionably', 'uncontrollable', 'uncontrollably',
                       'uncontrolled', 'uncorrected', 'uncover', 'uncovered', 'uncovering', 'uncovers', 'undeliverable',
                       'undelivered', 'undercapitalized', 'undercut', 'undercuts', 'undercutting', 'underestimate',
                       'underestimated', 'underestimates', 'underestimating', 'underestimation', 'underfunded',
                       'underinsured', 'undermine', 'undermined', 'undermines', 'undermining', 'underpaid',
                       'underpayment', 'underpayments', 'underpays', 'underperform', 'underperformance',
                       'underperformed', 'underperforming', 'underperforms', 'underproduced', 'underproduction',
                       'underreporting', 'understate', 'understated', 'understatement', 'understatements',
                       'understates', 'understating', 'underutilization', 'underutilized', 'undesirable', 'undesired',
                       'undetected', 'undetermined', 'undisclosed', 'undocumented', 'undue', 'unduly', 'uneconomic',
                       'uneconomical', 'uneconomically', 'unemployed', 'unemployment', 'unethical', 'unethically',
                       'unexcused', 'unexpected', 'unexpectedly', 'unfair', 'unfairly', 'unfavorability', 'unfavorable',
                       'unfavorably', 'unfavourable', 'unfeasible', 'unfit', 'unfitness', 'unforeseeable', 'unforeseen',
                       'unforseen', 'unfortunate', 'unfortunately', 'unfounded', 'unfriendly', 'unfulfilled',
                       'unfunded', 'uninsured', 'unintended', 'unintentional', 'unintentionally', 'unjust',
                       'unjustifiable', 'unjustifiably', 'unjustified', 'unjustly', 'unknowing', 'unknowingly',
                       'unlawful', 'unlawfully', 'unlicensed', 'unliquidated', 'unmarketable', 'unmerchantable',
                       'unmeritorious', 'unnecessarily', 'unnecessary', 'unneeded', 'unobtainable', 'unoccupied',
                       'unpaid', 'unperformed', 'unplanned', 'unpopular', 'unpredictability', 'unpredictable',
                       'unpredictably', 'unpredicted', 'unproductive', 'unprofitability', 'unprofitable', 'unqualified',
                       'unrealistic', 'unreasonable', 'unreasonableness', 'unreasonably', 'unreceptive',
                       'unrecoverable', 'unrecovered', 'unreimbursed', 'unreliable', 'unremedied', 'unreported',
                       'unresolved', 'unrest', 'unsafe', 'unsalable', 'unsaleable', 'unsatisfactory', 'unsatisfied',
                       'unsavory', 'unscheduled', 'unsellable', 'unsold', 'unsound', 'unstabilized', 'unstable',
                       'unsubstantiated', 'unsuccessful', 'unsuccessfully', 'unsuitability', 'unsuitable', 'unsuitably',
                       'unsuited', 'unsure', 'unsuspected', 'unsuspecting', 'unsustainable', 'untenable', 'untimely',
                       'untrusted', 'untruth', 'untruthful', 'untruthfully', 'untruthfulness', 'untruths', 'unusable',
                       'unwanted', 'unwarranted', 'unwelcome', 'unwilling', 'unwillingness', 'upset', 'urgency',
                       'urgent', 'usurious', 'usurp', 'usurped', 'usurping', 'usurps', 'usury', 'vandalism', 'verdict',
                       'verdicts', 'vetoed', 'victims', 'violate', 'violated', 'violates', 'violating', 'violation',
                       'violations', 'violative', 'violator', 'violators', 'violence', 'violent', 'violently',
                       'vitiate', 'vitiated', 'vitiates', 'vitiating', 'vitiation', 'voided', 'voiding', 'volatile',
                       'volatility', 'vulnerabilities', 'vulnerability', 'vulnerable', 'vulnerably', 'warn', 'warned',
                       'warning', 'warnings', 'warns', 'wasted', 'wasteful', 'wasting', 'weak', 'weaken', 'weakened',
                       'weakening', 'weakens', 'weaker', 'weakest', 'weakly', 'weakness', 'weaknesses', 'willfully',
                       'worries', 'worry', 'worrying', 'worse', 'worsen', 'worsened', 'worsening', 'worsens', 'worst',
                       'worthless', 'writedown', 'writedowns', 'writeoff', 'writeoffs', 'wrong', 'wrongdoing',
                       'wrongdoings', 'wrongful', 'wrongfully', 'wrongly', 'negative', 'negatives', 'fail', 'fails', 'failing', 'failure', 'weak', 'weakness', 'weaknesses',
                      'difficult', 'difficulty', 'hurdle', 'hurdles', 'obstacle', 'obstacles', 'slump', 'slumps',
                      'slumping', 'slumped', 'uncertain', 'uncertainty', 'unsettled', 'unfavorable', 'downturn',
                      'depressed', 'disappoint', 'disappoints', 'disappointing', 'disappointed', 'disappointment',
                      'risk', 'risks', 'risky', 'threat', 'threats', 'penalty', 'penalties', 'down', 'decrease',
                      'decreases', 'decreasing', 'decreased', 'decline', 'declines', 'declining', 'declined', 'fall',
                      'falls', 'falling', 'fell', 'fallen', 'drop', 'drops', 'dropping', 'dropped', 'deteriorate',
                      'deteriorates', 'deteriorating', 'deteriorated', 'worsen', 'worsens', 'worsening', 'weaken',
                      'weakens', 'weakening', 'weakened', 'worse', 'worst', 'low', 'lower', 'lowest', 'less', 'least',
                      'smaller', 'smallest', 'shrink', 'shrinks', 'shrinking', 'shrunk', 'below', 'under', 'challenge',
                      'challenges', 'challenging', 'challenged']

In [196]:
# Introduce negative financial keywords
Positive = ['able', 'abundance', 'abundant', 'acclaimed', 'accomplish', 'accomplished', 'accomplishes',
                       'accomplishing', 'accomplishment', 'accomplishments', 'achieve', 'achieved', 'achievement',
                       'achievements', 'achieves', 'achieving', 'adequately', 'advancement', 'advancements', 'advances',
                       'advancing', 'advantage', 'advantaged', 'advantageous', 'advantageously', 'advantages',
                       'alliance', 'alliances', 'assure', 'assured', 'assures', 'assuring', 'attain', 'attained',
                       'attaining', 'attainment', 'attainments', 'attains', 'attractive', 'attractiveness', 'beautiful',
                       'beautifully', 'beneficial', 'beneficially', 'benefit', 'benefited', 'benefiting', 'benefitted',
                       'benefitting', 'best', 'better', 'bolstered', 'bolstering', 'bolsters', 'boom', 'booming',
                       'boost', 'boosted', 'breakthrough', 'breakthroughs', 'brilliant', 'charitable', 'collaborate',
                       'collaborated', 'collaborates', 'collaborating', 'collaboration', 'collaborations',
                       'collaborative', 'collaborator', 'collaborators', 'compliment', 'complimentary', 'complimented',
                       'complimenting', 'compliments', 'conclusive', 'conclusively', 'conducive', 'confident',
                       'constructive', 'constructively', 'courteous', 'creative', 'creatively', 'creativeness',
                       'creativity', 'delight', 'delighted', 'delightful', 'delightfully', 'delighting', 'delights',
                       'dependability', 'dependable', 'desirable', 'desired', 'despite', 'destined', 'diligent',
                       'diligently', 'distinction', 'distinctions', 'distinctive', 'distinctively', 'distinctiveness',
                       'dream', 'easier', 'easily', 'easy', 'effective', 'efficiencies', 'efficiency', 'efficient',
                       'efficiently', 'empower', 'empowered', 'empowering', 'empowers', 'enable', 'enabled', 'enables',
                       'enabling', 'encouraged', 'encouragement', 'encourages', 'encouraging', 'enhance', 'enhanced',
                       'enhancement', 'enhancements', 'enhances', 'enhancing', 'enjoy', 'enjoyable', 'enjoyably',
                       'enjoyed', 'enjoying', 'enjoyment', 'enjoys', 'enthusiasm', 'enthusiastic', 'enthusiastically',
                       'excellence', 'excellent', 'excelling', 'excels', 'exceptional', 'exceptionally', 'excited',
                       'excitement', 'exciting', 'exclusive', 'exclusively', 'exclusiveness', 'exclusives',
                       'exclusivity', 'exemplary', 'fantastic', 'favorable', 'favorably', 'favored', 'favoring',
                       'favorite', 'favorites', 'friendly', 'gain', 'gained', 'gaining', 'gains', 'good', 'great',
                       'greater', 'greatest', 'greatly', 'greatness', 'happiest', 'happily', 'happiness', 'happy',
                       'highest', 'honor', 'honorable', 'honored', 'honoring', 'honors', 'ideal', 'impress',
                       'impressed', 'impresses', 'impressing', 'impressive', 'impressively', 'improve', 'improved',
                       'improvement', 'improvements', 'improves', 'improving', 'incredible', 'incredibly',
                       'influential', 'informative', 'ingenuity', 'innovate', 'innovated', 'innovates', 'innovating',
                       'innovation', 'innovations', 'innovative', 'innovativeness', 'innovator', 'innovators',
                       'insightful', 'inspiration', 'inspirational', 'integrity', 'invent', 'invented', 'inventing',
                       'invention', 'inventions', 'inventive', 'inventiveness', 'inventor', 'inventors', 'leadership',
                       'leading', 'loyal', 'lucrative', 'meritorious', 'opportunities', 'opportunity', 'optimistic',
                       'outperform', 'outperformed', 'outperforming', 'outperforms', 'perfect', 'perfected',
                       'perfectly', 'perfects', 'pleasant', 'pleasantly', 'pleased', 'pleasure', 'plentiful', 'popular',
                       'popularity', 'positive', 'positively', 'preeminence', 'preeminent', 'premier', 'premiere',
                       'prestige', 'prestigious', 'proactive', 'proactively', 'proficiency', 'proficient',
                       'proficiently', 'profitability', 'profitable', 'profitably', 'progress', 'progressed',
                       'progresses', 'progressing', 'prospered', 'prospering', 'prosperity', 'prosperous', 'prospers',
                       'rebound', 'rebounded', 'rebounding', 'receptive', 'regain', 'regained', 'regaining', 'resolve',
                       'revolutionize', 'revolutionized', 'revolutionizes', 'revolutionizing', 'reward', 'rewarded',
                       'rewarding', 'rewards', 'satisfaction', 'satisfactorily', 'satisfactory', 'satisfied',
                       'satisfies', 'satisfy', 'satisfying', 'smooth', 'smoothing', 'smoothly', 'smooths', 'solves',
                       'solving', 'spectacular', 'spectacularly', 'stability', 'stabilization', 'stabilizations',
                       'stabilize', 'stabilized', 'stabilizes', 'stabilizing', 'stable', 'strength', 'strengthen',
                       'strengthened', 'strengthening', 'strengthens', 'strengths', 'strong', 'stronger', 'strongest',
                       'succeed', 'succeeded', 'succeeding', 'succeeds', 'success', 'successes', 'successful',
                       'successfully', 'superior', 'surpass', 'surpassed', 'surpasses', 'surpassing', 'transparency',
                       'tremendous', 'tremendously', 'unmatched', 'unparalleled', 'unsurpassed', 'upturn', 'upturns',
                       'valuable', 'versatile', 'versatility', 'vibrancy', 'vibrant', 'win', 'winner', 'winners',
                       'winning', 'worthy', 'positive', 'positives', 'success', 'successes', 'successful', 'succeed', 'succeeds',
                      'succeeding', 'succeeded', 'accomplish', 'accomplishes', 'accomplishing', 'accomplished',
                      'accomplishment', 'accomplishments', 'strong', 'strength', 'strengths', 'certain', 'certainty',
                      'definite', 'solid', 'excellent', 'good', 'leading', 'achieve', 'achieves', 'achieved',
                      'achieving', 'achievement', 'achievements', 'progress', 'progressing', 'deliver', 'delivers',
                      'delivered', 'delivering', 'leader', 'leading', 'pleased', 'reward', 'rewards', 'rewarding',
                      'rewarded', 'opportunity', 'opportunities', 'enjoy', 'enjoys', 'enjoying', 'enjoyed',
                      'encouraged', 'encouraging', 'up', 'increase', 'increases', 'increasing', 'increased', 'rise',
                      'rises', 'rising', 'rose', 'risen', 'improve', 'improves', 'improving', 'improved', 'improvement',
                      'improvements', 'strengthen', 'strengthens', 'strengthening', 'strengthened', 'stronger',
                      'strongest', 'better', 'best', 'more', 'most', 'above', 'record', 'high', 'higher', 'highest',
                      'greater', 'greatest', 'larger', 'largest', 'grow', 'grows', 'growing', 'grew', 'grown', 'growth',
                      'expand', 'expands', 'expanding', 'expanded', 'expansion', 'exceed', 'exceeds', 'exceeded',
                      'exceeding', 'beat', 'beats', 'beating']

In [200]:
# Sentiment analysis using the above negative and positive keywords.
sentbydaypos=defaultdict(int)
sentbydayneg=defaultdict(int)
sentbyday=defaultdict(int)
for index,row in WSB_reddits.iterrows():
    for word in row['text'].split(' '):
#         print(word)
        if word in Positive:
            sentbydaypos[row['day']] += 1
            sentbyday[row['day']] += 1
        if word in Negative:
            sentbydayneg[row['day']] += 1
            sentbyday[row['day']] =  sentbyday[row['day']] -1
            
#     break

In [208]:
# positive sentiment counts of frequency of positive keywords by day
sentbydaypos

defaultdict(int,
            {Timestamp('2016-01-01 00:00:00'): 23,
             Timestamp('2016-01-02 00:00:00'): 2,
             Timestamp('2016-01-03 00:00:00'): 88,
             Timestamp('2016-01-04 00:00:00'): 28,
             Timestamp('2016-01-05 00:00:00'): 19,
             Timestamp('2016-01-06 00:00:00'): 39,
             Timestamp('2016-01-07 00:00:00'): 79,
             Timestamp('2016-01-08 00:00:00'): 75,
             Timestamp('2016-01-09 00:00:00'): 9,
             Timestamp('2016-01-10 00:00:00'): 17,
             Timestamp('2016-01-11 00:00:00'): 25,
             Timestamp('2016-01-12 00:00:00'): 45,
             Timestamp('2016-01-13 00:00:00'): 32,
             Timestamp('2016-01-14 00:00:00'): 40,
             Timestamp('2016-01-15 00:00:00'): 52,
             Timestamp('2016-01-16 00:00:00'): 49,
             Timestamp('2016-01-17 00:00:00'): 40,
             Timestamp('2016-01-18 00:00:00'): 59,
             Timestamp('2016-01-19 00:00:00'): 64,
             Timestamp('2016-01-20 00:00:00'): 78,
             Timestamp('2016-01-21 00:00:00'): 77,
             Timestamp('2016-01-22 00:00:00'): 102,
             Timestamp('2016-01-23 00:00:00'): 22,
             Timestamp('2016-01-24 00:00:00'): 21,
             Timestamp('2016-01-25 00:00:00'): 26,
             Timestamp('2016-01-26 00:00:00'): 72,
             Timestamp('2016-01-27 00:00:00'): 42,
             Timestamp('2016-01-28 00:00:00'): 42,
             Timestamp('2016-01-29 00:00:00'): 30,
             Timestamp('2016-01-30 00:00:00'): 14,
             Timestamp('2016-01-31 00:00:00'): 46,
             Timestamp('2016-02-01 00:00:00'): 23,
             Timestamp('2016-02-02 00:00:00'): 33,
             Timestamp('2016-02-03 00:00:00'): 46,
             Timestamp('2016-02-04 00:00:00'): 25,
             Timestamp('2016-02-05 00:00:00'): 47,
             Timestamp('2016-02-06 00:00:00'): 38,
             Timestamp('2016-02-07 00:00:00'): 13,
             Timestamp('2016-02-08 00:00:00'): 36,
             Timestamp('2016-02-09 00:00:00'): 52,
             Timestamp('2016-02-10 00:00:00'): 47,
             Timestamp('2016-02-11 00:00:00'): 57,
             Timestamp('2016-02-12 00:00:00'): 58,
             Timestamp('2016-02-13 00:00:00'): 12,
             Timestamp('2016-02-14 00:00:00'): 11,
             Timestamp('2016-02-15 00:00:00'): 9,
             Timestamp('2016-02-16 00:00:00'): 48,
             Timestamp('2016-02-17 00:00:00'): 37,
             Timestamp('2016-02-18 00:00:00'): 53,
             Timestamp('2016-02-19 00:00:00'): 59,
             Timestamp('2016-02-20 00:00:00'): 10,
             Timestamp('2016-02-21 00:00:00'): 15,
             Timestamp('2016-02-22 00:00:00'): 32,
             Timestamp('2016-02-23 00:00:00'): 13,
             Timestamp('2016-02-24 00:00:00'): 35,
             Timestamp('2016-02-25 00:00:00'): 65,
             Timestamp('2016-02-26 00:00:00'): 31,
             Timestamp('2016-02-27 00:00:00'): 25,
             Timestamp('2016-02-28 00:00:00'): 13,
             Timestamp('2016-02-29 00:00:00'): 32,
             Timestamp('2016-03-01 00:00:00'): 40,
             Timestamp('2016-03-02 00:00:00'): 62,
             Timestamp('2016-03-03 00:00:00'): 83,
             Timestamp('2016-03-04 00:00:00'): 68,
             Timestamp('2016-03-05 00:00:00'): 15,
             Timestamp('2016-03-06 00:00:00'): 6,
             Timestamp('2016-03-07 00:00:00'): 49,
             Timestamp('2016-03-08 00:00:00'): 30,
             Timestamp('2016-03-09 00:00:00'): 52,
             Timestamp('2016-03-10 00:00:00'): 23,
             Timestamp('2016-03-11 00:00:00'): 23,
             Timestamp('2016-03-12 00:00:00'): 7,
             Timestamp('2016-03-13 00:00:00'): 61,
             Timestamp('2016-03-14 00:00:00'): 27,
             Timestamp('2016-03-15 00:00:00'): 49,
             Timestamp('2016-03-16 00:00:00'): 34,
             Timestamp('2016-03-17 00:00:00'): 77,
             Timestamp('2016-03-18 00:00:00'): 54,
             Timestamp('2016-03-19 00:00:00'): 15,
             Timestamp('2016-03-20 00:00:00'): 89,
             Timestamp('2016-03-21 00:00:00'): 45,
             Timestamp('2016-03-22 00:00:00'): 77,
             Timestamp('2016-03-23 00:00:00'): 70,
             Timestamp('2016-03-24 00:00:00'): 50,
             Timestamp('2016-03-25 00:00:00'): 38,
             Timestamp('2016-03-26 00:00:00'): 4,
             Timestamp('2016-03-27 00:00:00'): 24,
             Timestamp('2016-03-28 00:00:00'): 63,
             Timestamp('2016-03-29 00:00:00'): 97,
             Timestamp('2016-03-30 00:00:00'): 64,
             Timestamp('2016-03-31 00:00:00'): 72,
             Timestamp('2016-04-01 00:00:00'): 115,
             Timestamp('2016-04-02 00:00:00'): 27,
             Timestamp('2016-04-03 00:00:00'): 18,
             Timestamp('2016-04-04 00:00:00'): 64,
             Timestamp('2016-04-05 00:00:00'): 84,
             Timestamp('2016-04-06 00:00:00'): 67,
             Timestamp('2016-04-07 00:00:00'): 56,
             Timestamp('2016-04-08 00:00:00'): 57,
             Timestamp('2016-04-09 00:00:00'): 49,
             Timestamp('2016-04-10 00:00:00'): 36,
             Timestamp('2016-04-11 00:00:00'): 116,
             Timestamp('2016-04-12 00:00:00'): 108,
             Timestamp('2016-04-13 00:00:00'): 83,
             Timestamp('2016-04-14 00:00:00'): 51,
             Timestamp('2016-04-15 00:00:00'): 49,
             Timestamp('2016-04-16 00:00:00'): 45,
             Timestamp('2016-04-17 00:00:00'): 14,
             Timestamp('2016-04-18 00:00:00'): 90,
             Timestamp('2016-04-19 00:00:00'): 80,
             Timestamp('2016-04-20 00:00:00'): 90,
             Timestamp('2016-04-21 00:00:00'): 73,
             Timestamp('2016-04-22 00:00:00'): 54,
             Timestamp('2016-04-23 00:00:00'): 30,
             Timestamp('2016-04-24 00:00:00'): 26,
             Timestamp('2016-04-25 00:00:00'): 53,
             Timestamp('2016-04-26 00:00:00'): 83,
             Timestamp('2016-04-27 00:00:00'): 52,
             Timestamp('2016-04-28 00:00:00'): 43,
             Timestamp('2016-04-29 00:00:00'): 62,
             Timestamp('2016-04-30 00:00:00'): 24,
             Timestamp('2016-05-01 00:00:00'): 26,
             Timestamp('2016-05-02 00:00:00'): 43,
             Timestamp('2016-05-03 00:00:00'): 77,
             Timestamp('2016-05-04 00:00:00'): 43,
             Timestamp('2016-05-05 00:00:00'): 79,
             Timestamp('2016-05-06 00:00:00'): 65,
             Timestamp('2016-05-07 00:00:00'): 17,
             Timestamp('2016-05-08 00:00:00'): 18,
             Timestamp('2016-05-09 00:00:00'): 36,
             Timestamp('2016-05-10 00:00:00'): 57,
             Timestamp('2016-05-11 00:00:00'): 68,
             Timestamp('2016-05-12 00:00:00'): 50,
             Timestamp('2016-05-13 00:00:00'): 75,
             Timestamp('2016-05-14 00:00:00'): 29,
             Timestamp('2016-05-15 00:00:00'): 10,
             Timestamp('2016-05-16 00:00:00'): 45,
             Timestamp('2016-05-17 00:00:00'): 78,
             Timestamp('2016-05-18 00:00:00'): 47,
             Timestamp('2016-05-19 00:00:00'): 31,
             Timestamp('2016-05-20 00:00:00'): 51,
             Timestamp('2016-05-21 00:00:00'): 50,
             Timestamp('2016-05-22 00:00:00'): 11,
             Timestamp('2016-05-23 00:00:00'): 61,
             Timestamp('2016-05-24 00:00:00'): 56,
             Timestamp('2016-05-25 00:00:00'): 55,
             Timestamp('2016-05-26 00:00:00'): 73,
             Timestamp('2016-05-27 00:00:00'): 71,
             Timestamp('2016-05-28 00:00:00'): 17,
             Timestamp('2016-05-29 00:00:00'): 21,
             Timestamp('2016-05-30 00:00:00'): 42,
             Timestamp('2016-05-31 00:00:00'): 54,
             Timestamp('2016-06-01 00:00:00'): 62,
             Timestamp('2016-06-02 00:00:00'): 33,
             Timestamp('2016-06-03 00:00:00'): 15,
             Timestamp('2016-06-04 00:00:00'): 10,
             Timestamp('2016-06-05 00:00:00'): 14,
             Timestamp('2016-06-06 00:00:00'): 42,
             Timestamp('2016-06-07 00:00:00'): 135,
             Timestamp('2016-06-08 00:00:00'): 57,
             Timestamp('2016-06-09 00:00:00'): 96,
             Timestamp('2016-06-10 00:00:00'): 24,
             Timestamp('2016-06-11 00:00:00'): 11,
             Timestamp('2016-06-12 00:00:00'): 28,
             Timestamp('2016-06-13 00:00:00'): 60,
             Timestamp('2016-06-14 00:00:00'): 35,
             Timestamp('2016-06-15 00:00:00'): 33,
             Timestamp('2016-06-16 00:00:00'): 48,
             Timestamp('2016-06-17 00:00:00'): 69,
             Timestamp('2016-06-18 00:00:00'): 40,
             Timestamp('2016-06-19 00:00:00'): 14,
             Timestamp('2016-06-20 00:00:00'): 49,
             Timestamp('2016-06-21 00:00:00'): 90,
             Timestamp('2016-06-22 00:00:00'): 69,
             Timestamp('2016-06-23 00:00:00'): 35,
             Timestamp('2016-06-24 00:00:00'): 72,
             Timestamp('2016-06-25 00:00:00'): 125,
             Timestamp('2016-06-26 00:00:00'): 42,
             Timestamp('2016-06-27 00:00:00'): 51,
             Timestamp('2016-06-28 00:00:00'): 94,
             Timestamp('2016-06-29 00:00:00'): 71,
             Timestamp('2016-06-30 00:00:00'): 100,
             Timestamp('2016-07-01 00:00:00'): 71,
             Timestamp('2016-07-02 00:00:00'): 57,
             Timestamp('2016-07-03 00:00:00'): 16,
             Timestamp('2016-07-04 00:00:00'): 26,
             Timestamp('2016-07-05 00:00:00'): 34,
             Timestamp('2016-07-06 00:00:00'): 48,
             Timestamp('2016-07-07 00:00:00'): 103,
             Timestamp('2016-07-08 00:00:00'): 91,
             Timestamp('2016-07-09 00:00:00'): 19,
             Timestamp('2016-07-10 00:00:00'): 22,
             Timestamp('2016-07-11 00:00:00'): 61,
             Timestamp('2016-07-12 00:00:00'): 98,
             Timestamp('2016-07-13 00:00:00'): 55,
             Timestamp('2016-07-14 00:00:00'): 141,
             Timestamp('2016-07-15 00:00:00'): 48,
             Timestamp('2016-07-16 00:00:00'): 63,
             Timestamp('2016-07-17 00:00:00'): 17,
             Timestamp('2016-07-18 00:00:00'): 84,
             Timestamp('2016-07-19 00:00:00'): 127,
             Timestamp('2016-07-20 00:00:00'): 103,
             Timestamp('2016-07-21 00:00:00'): 78,
             Timestamp('2016-07-22 00:00:00'): 91,
             Timestamp('2016-07-23 00:00:00'): 22,
             Timestamp('2016-07-24 00:00:00'): 28,
             Timestamp('2016-07-25 00:00:00'): 125,
             Timestamp('2016-07-26 00:00:00'): 66,
             Timestamp('2016-07-27 00:00:00'): 124,
             Timestamp('2016-07-28 00:00:00'): 91,
             Timestamp('2016-07-29 00:00:00'): 65,
             Timestamp('2016-07-30 00:00:00'): 29,
             Timestamp('2016-07-31 00:00:00'): 36,
             Timestamp('2016-08-01 00:00:00'): 36,
             Timestamp('2016-08-02 00:00:00'): 103,
             Timestamp('2016-08-03 00:00:00'): 51,
             Timestamp('2016-08-04 00:00:00'): 49,
             Timestamp('2016-08-05 00:00:00'): 53,
             Timestamp('2016-08-06 00:00:00'): 14,
             Timestamp('2016-08-07 00:00:00'): 10,
             Timestamp('2016-08-08 00:00:00'): 54,
             Timestamp('2016-08-09 00:00:00'): 57,
             Timestamp('2016-08-10 00:00:00'): 72,
             Timestamp('2016-08-11 00:00:00'): 80,
             Timestamp('2016-08-12 00:00:00'): 67,
             Timestamp('2016-08-13 00:00:00'): 31,
             Timestamp('2016-08-14 00:00:00'): 26,
             Timestamp('2016-08-15 00:00:00'): 48,
             Timestamp('2016-08-16 00:00:00'): 123,
             Timestamp('2016-08-17 00:00:00'): 66,
             Timestamp('2016-08-18 00:00:00'): 59,
             Timestamp('2016-08-19 00:00:00'): 67,
             Timestamp('2016-08-20 00:00:00'): 27,
             Timestamp('2016-08-21 00:00:00'): 45,
             Timestamp('2016-08-22 00:00:00'): 47,
             Timestamp('2016-08-23 00:00:00'): 64,
             Timestamp('2016-08-24 00:00:00'): 114,
             Timestamp('2016-08-25 00:00:00'): 53,
             Timestamp('2016-08-26 00:00:00'): 97,
             Timestamp('2016-08-27 00:00:00'): 34,
             Timestamp('2016-08-28 00:00:00'): 19,
             Timestamp('2016-08-29 00:00:00'): 55,
             Timestamp('2016-08-30 00:00:00'): 82,
             Timestamp('2016-08-31 00:00:00'): 38,
             Timestamp('2016-09-01 00:00:00'): 133,
             Timestamp('2016-09-02 00:00:00'): 61,
             Timestamp('2016-09-03 00:00:00'): 35,
             Timestamp('2016-09-04 00:00:00'): 18,
             Timestamp('2016-09-05 00:00:00'): 19,
             Timestamp('2016-09-06 00:00:00'): 64,
             Timestamp('2016-09-07 00:00:00'): 53,
             Timestamp('2016-09-08 00:00:00'): 64,
             Timestamp('2016-09-09 00:00:00'): 52,
             Timestamp('2016-09-10 00:00:00'): 35,
             Timestamp('2016-09-11 00:00:00'): 11,
             Timestamp('2016-09-12 00:00:00'): 60,
             Timestamp('2016-09-13 00:00:00'): 59,
             Timestamp('2016-09-14 00:00:00'): 77,
             Timestamp('2016-09-15 00:00:00'): 75,
             Timestamp('2016-09-16 00:00:00'): 114,
             Timestamp('2016-09-17 00:00:00'): 33,
             Timestamp('2016-09-18 00:00:00'): 6,
             Timestamp('2016-09-19 00:00:00'): 31,
             Timestamp('2016-09-20 00:00:00'): 120,
             Timestamp('2016-09-21 00:00:00'): 71,
             Timestamp('2016-09-22 00:00:00'): 39,
             Timestamp('2016-09-23 00:00:00'): 53,
             Timestamp('2016-09-24 00:00:00'): 22,
             Timestamp('2016-09-25 00:00:00'): 5,
             Timestamp('2016-09-26 00:00:00'): 43,
             Timestamp('2016-09-27 00:00:00'): 106,
             Timestamp('2016-09-28 00:00:00'): 48,
             Timestamp('2016-09-29 00:00:00'): 40,
             Timestamp('2016-09-30 00:00:00'): 63,
             Timestamp('2016-10-01 00:00:00'): 48,
             Timestamp('2016-10-02 00:00:00'): 8,
             Timestamp('2016-10-03 00:00:00'): 24,
             Timestamp('2016-10-04 00:00:00'): 77,
             Timestamp('2016-10-05 00:00:00'): 45,
             Timestamp('2016-10-06 00:00:00'): 83,
             Timestamp('2016-10-07 00:00:00'): 80,
             Timestamp('2016-10-08 00:00:00'): 10,
             Timestamp('2016-10-09 00:00:00'): 7,
             Timestamp('2016-10-10 00:00:00'): 34,
             Timestamp('2016-10-11 00:00:00'): 27,
             Timestamp('2016-10-12 00:00:00'): 35,
             Timestamp('2016-10-13 00:00:00'): 84,
             Timestamp('2016-10-14 00:00:00'): 33,
             Timestamp('2016-10-15 00:00:00'): 20,
             Timestamp('2016-10-16 00:00:00'): 19,
             Timestamp('2016-10-17 00:00:00'): 33,
             Timestamp('2016-10-18 00:00:00'): 21,
             Timestamp('2016-10-19 00:00:00'): 69,
             Timestamp('2016-10-20 00:00:00'): 74,
             Timestamp('2016-10-21 00:00:00'): 53,
             Timestamp('2016-10-22 00:00:00'): 35,
             Timestamp('2016-10-23 00:00:00'): 37,
             Timestamp('2016-10-24 00:00:00'): 82,
             Timestamp('2016-10-25 00:00:00'): 41,
             Timestamp('2016-10-26 00:00:00'): 26,
             Timestamp('2016-10-27 00:00:00'): 60,
             Timestamp('2016-10-28 00:00:00'): 59,
             Timestamp('2016-10-29 00:00:00'): 25,
             Timestamp('2016-10-30 00:00:00'): 10,
             Timestamp('2016-10-31 00:00:00'): 18,
             Timestamp('2016-11-01 00:00:00'): 45,
             Timestamp('2016-11-02 00:00:00'): 51,
             Timestamp('2016-11-03 00:00:00'): 82,
             Timestamp('2016-11-04 00:00:00'): 30,
             Timestamp('2016-11-05 00:00:00'): 41,
             Timestamp('2016-11-06 00:00:00'): 17,
             Timestamp('2016-11-07 00:00:00'): 33,
             Timestamp('2016-11-08 00:00:00'): 74,
             Timestamp('2016-11-09 00:00:00'): 68,
             Timestamp('2016-11-10 00:00:00'): 70,
             Timestamp('2016-11-11 00:00:00'): 52,
             Timestamp('2016-11-12 00:00:00'): 18,
             Timestamp('2016-11-13 00:00:00'): 19,
             Timestamp('2016-11-14 00:00:00'): 45,
             Timestamp('2016-11-15 00:00:00'): 104,
             Timestamp('2016-11-16 00:00:00'): 80,
             Timestamp('2016-11-17 00:00:00'): 107,
             Timestamp('2016-11-18 00:00:00'): 83,
             Timestamp('2016-11-19 00:00:00'): 14,
             Timestamp('2016-11-20 00:00:00'): 13,
             Timestamp('2016-11-21 00:00:00'): 23,
             Timestamp('2016-11-22 00:00:00'): 61,
             Timestamp('2016-11-23 00:00:00'): 35,
             Timestamp('2016-11-24 00:00:00'): 40,
             Timestamp('2016-11-25 00:00:00'): 16,
             Timestamp('2016-11-26 00:00:00'): 9,
             Timestamp('2016-11-27 00:00:00'): 5,
             Timestamp('2016-11-28 00:00:00'): 61,
             Timestamp('2016-11-29 00:00:00'): 38,
             Timestamp('2016-11-30 00:00:00'): 6,
             Timestamp('2016-12-01 00:00:00'): 60,
             Timestamp('2016-12-02 00:00:00'): 24,
             Timestamp('2016-12-03 00:00:00'): 27,
             Timestamp('2016-12-04 00:00:00'): 52,
             Timestamp('2016-12-05 00:00:00'): 44,
             Timestamp('2016-12-06 00:00:00'): 71,
             Timestamp('2016-12-07 00:00:00'): 15,
             Timestamp('2016-12-16 00:00:00'): 95,
             Timestamp('2016-12-17 00:00:00'): 8,
             Timestamp('2016-12-18 00:00:00'): 12,
             Timestamp('2016-12-19 00:00:00'): 34,
             Timestamp('2016-12-20 00:00:00'): 30,
             Timestamp('2016-12-21 00:00:00'): 68,
             Timestamp('2016-12-22 00:00:00'): 59,
             Timestamp('2016-12-23 00:00:00'): 41,
             Timestamp('2016-12-24 00:00:00'): 9,
             Timestamp('2016-12-25 00:00:00'): 31,
             Timestamp('2016-12-26 00:00:00'): 8,
             Timestamp('2016-12-27 00:00:00'): 27,
             Timestamp('2016-12-28 00:00:00'): 15,
             Timestamp('2016-12-29 00:00:00'): 21,
             Timestamp('2016-12-30 00:00:00'): 25,
             Timestamp('2016-12-31 00:00:00'): 21,
             Timestamp('2017-01-01 00:00:00'): 8,
             Timestamp('2017-01-02 00:00:00'): 19,
             Timestamp('2017-01-03 00:00:00'): 12,
             Timestamp('2017-01-04 00:00:00'): 35,
             Timestamp('2017-01-05 00:00:00'): 31,
             Timestamp('2017-01-06 00:00:00'): 102,
             Timestamp('2017-01-07 00:00:00'): 20,
             Timestamp('2017-01-08 00:00:00'): 41,
             Timestamp('2017-01-09 00:00:00'): 120,
             Timestamp('2017-01-10 00:00:00'): 50,
             Timestamp('2017-01-11 00:00:00'): 93,
             Timestamp('2017-01-12 00:00:00'): 76,
             Timestamp('2017-01-13 00:00:00'): 124,
             Timestamp('2017-01-14 00:00:00'): 7,
             Timestamp('2017-01-15 00:00:00'): 12,
             Timestamp('2017-01-16 00:00:00'): 40,
             Timestamp('2017-01-17 00:00:00'): 90,
             Timestamp('2017-01-18 00:00:00'): 54,
             Timestamp('2017-01-19 00:00:00'): 126,
             Timestamp('2017-01-20 00:00:00'): 21,
             Timestamp('2017-01-21 00:00:00'): 22,
             Timestamp('2017-01-22 00:00:00'): 26,
             Timestamp('2017-01-23 00:00:00'): 34,
             Timestamp('2017-01-24 00:00:00'): 31,
             Timestamp('2017-01-25 00:00:00'): 65,
             Timestamp('2017-01-26 00:00:00'): 71,
             Timestamp('2017-01-27 00:00:00'): 250,
             Timestamp('2017-01-28 00:00:00'): 10,
             Timestamp('2017-01-29 00:00:00'): 40,
             Timestamp('2017-01-30 00:00:00'): 51,
             Timestamp('2017-01-31 00:00:00'): 78,
             Timestamp('2017-02-01 00:00:00'): 55,
             Timestamp('2017-02-02 00:00:00'): 59,

In [209]:
# negative sentiment counts of frequency of negative keywords by day
sentbydayneg

defaultdict(int,
            {Timestamp('2016-01-01 00:00:00'): 6,
             Timestamp('2016-01-02 00:00:00'): 2,
             Timestamp('2016-01-03 00:00:00'): 58,
             Timestamp('2016-01-04 00:00:00'): 30,
             Timestamp('2016-01-05 00:00:00'): 27,
             Timestamp('2016-01-06 00:00:00'): 62,
             Timestamp('2016-01-07 00:00:00'): 84,
             Timestamp('2016-01-08 00:00:00'): 76,
             Timestamp('2016-01-09 00:00:00'): 18,
             Timestamp('2016-01-10 00:00:00'): 2,
             Timestamp('2016-01-11 00:00:00'): 26,
             Timestamp('2016-01-12 00:00:00'): 43,
             Timestamp('2016-01-13 00:00:00'): 24,
             Timestamp('2016-01-14 00:00:00'): 32,
             Timestamp('2016-01-15 00:00:00'): 75,
             Timestamp('2016-01-16 00:00:00'): 32,
             Timestamp('2016-01-17 00:00:00'): 26,
             Timestamp('2016-01-18 00:00:00'): 76,
             Timestamp('2016-01-19 00:00:00'): 52,
             Timestamp('2016-01-20 00:00:00'): 66,
             Timestamp('2016-01-21 00:00:00'): 62,
             Timestamp('2016-01-22 00:00:00'): 65,
             Timestamp('2016-01-23 00:00:00'): 13,
             Timestamp('2016-01-24 00:00:00'): 8,
             Timestamp('2016-01-25 00:00:00'): 15,
             Timestamp('2016-01-26 00:00:00'): 72,
             Timestamp('2016-01-27 00:00:00'): 36,
             Timestamp('2016-01-28 00:00:00'): 33,
             Timestamp('2016-01-29 00:00:00'): 33,
             Timestamp('2016-01-30 00:00:00'): 11,
             Timestamp('2016-01-31 00:00:00'): 40,
             Timestamp('2016-02-01 00:00:00'): 24,
             Timestamp('2016-02-02 00:00:00'): 26,
             Timestamp('2016-02-03 00:00:00'): 32,
             Timestamp('2016-02-04 00:00:00'): 19,
             Timestamp('2016-02-05 00:00:00'): 39,
             Timestamp('2016-02-06 00:00:00'): 42,
             Timestamp('2016-02-07 00:00:00'): 16,
             Timestamp('2016-02-08 00:00:00'): 40,
             Timestamp('2016-02-09 00:00:00'): 49,
             Timestamp('2016-02-10 00:00:00'): 35,
             Timestamp('2016-02-11 00:00:00'): 61,
             Timestamp('2016-02-12 00:00:00'): 42,
             Timestamp('2016-02-13 00:00:00'): 13,
             Timestamp('2016-02-14 00:00:00'): 13,
             Timestamp('2016-02-15 00:00:00'): 5,
             Timestamp('2016-02-16 00:00:00'): 54,
             Timestamp('2016-02-17 00:00:00'): 26,
             Timestamp('2016-02-18 00:00:00'): 42,
             Timestamp('2016-02-19 00:00:00'): 35,
             Timestamp('2016-02-20 00:00:00'): 8,
             Timestamp('2016-02-21 00:00:00'): 33,
             Timestamp('2016-02-22 00:00:00'): 28,
             Timestamp('2016-02-23 00:00:00'): 11,
             Timestamp('2016-02-24 00:00:00'): 20,
             Timestamp('2016-02-25 00:00:00'): 48,
             Timestamp('2016-02-26 00:00:00'): 27,
             Timestamp('2016-02-27 00:00:00'): 25,
             Timestamp('2016-02-28 00:00:00'): 11,
             Timestamp('2016-02-29 00:00:00'): 29,
             Timestamp('2016-03-01 00:00:00'): 24,
             Timestamp('2016-03-02 00:00:00'): 34,
             Timestamp('2016-03-03 00:00:00'): 89,
             Timestamp('2016-03-04 00:00:00'): 70,
             Timestamp('2016-03-05 00:00:00'): 4,
             Timestamp('2016-03-06 00:00:00'): 4,
             Timestamp('2016-03-07 00:00:00'): 48,
             Timestamp('2016-03-08 00:00:00'): 33,
             Timestamp('2016-03-09 00:00:00'): 46,
             Timestamp('2016-03-10 00:00:00'): 16,
             Timestamp('2016-03-11 00:00:00'): 15,
             Timestamp('2016-03-12 00:00:00'): 4,
             Timestamp('2016-03-13 00:00:00'): 48,
             Timestamp('2016-03-14 00:00:00'): 31,
             Timestamp('2016-03-15 00:00:00'): 34,
             Timestamp('2016-03-16 00:00:00'): 42,
             Timestamp('2016-03-17 00:00:00'): 55,
             Timestamp('2016-03-18 00:00:00'): 54,
             Timestamp('2016-03-19 00:00:00'): 9,
             Timestamp('2016-03-20 00:00:00'): 61,
             Timestamp('2016-03-21 00:00:00'): 30,
             Timestamp('2016-03-22 00:00:00'): 57,
             Timestamp('2016-03-23 00:00:00'): 58,
             Timestamp('2016-03-24 00:00:00'): 70,
             Timestamp('2016-03-25 00:00:00'): 38,
             Timestamp('2016-03-26 00:00:00'): 2,
             Timestamp('2016-03-27 00:00:00'): 6,
             Timestamp('2016-03-28 00:00:00'): 41,
             Timestamp('2016-03-29 00:00:00'): 42,
             Timestamp('2016-03-30 00:00:00'): 69,
             Timestamp('2016-03-31 00:00:00'): 80,
             Timestamp('2016-04-01 00:00:00'): 62,
             Timestamp('2016-04-02 00:00:00'): 19,
             Timestamp('2016-04-03 00:00:00'): 14,
             Timestamp('2016-04-04 00:00:00'): 41,
             Timestamp('2016-04-05 00:00:00'): 58,
             Timestamp('2016-04-06 00:00:00'): 46,
             Timestamp('2016-04-07 00:00:00'): 37,
             Timestamp('2016-04-08 00:00:00'): 38,
             Timestamp('2016-04-09 00:00:00'): 42,
             Timestamp('2016-04-10 00:00:00'): 35,
             Timestamp('2016-04-11 00:00:00'): 97,
             Timestamp('2016-04-12 00:00:00'): 69,
             Timestamp('2016-04-13 00:00:00'): 68,
             Timestamp('2016-04-14 00:00:00'): 43,
             Timestamp('2016-04-15 00:00:00'): 50,
             Timestamp('2016-04-16 00:00:00'): 45,
             Timestamp('2016-04-17 00:00:00'): 9,
             Timestamp('2016-04-18 00:00:00'): 59,
             Timestamp('2016-04-19 00:00:00'): 102,
             Timestamp('2016-04-20 00:00:00'): 83,
             Timestamp('2016-04-21 00:00:00'): 69,
             Timestamp('2016-04-22 00:00:00'): 43,
             Timestamp('2016-04-23 00:00:00'): 23,
             Timestamp('2016-04-24 00:00:00'): 15,
             Timestamp('2016-04-25 00:00:00'): 45,
             Timestamp('2016-04-26 00:00:00'): 56,
             Timestamp('2016-04-27 00:00:00'): 37,
             Timestamp('2016-04-28 00:00:00'): 38,
             Timestamp('2016-04-29 00:00:00'): 58,
             Timestamp('2016-04-30 00:00:00'): 20,
             Timestamp('2016-05-01 00:00:00'): 24,
             Timestamp('2016-05-02 00:00:00'): 23,
             Timestamp('2016-05-03 00:00:00'): 58,
             Timestamp('2016-05-04 00:00:00'): 17,
             Timestamp('2016-05-05 00:00:00'): 47,
             Timestamp('2016-05-06 00:00:00'): 49,
             Timestamp('2016-05-07 00:00:00'): 15,
             Timestamp('2016-05-08 00:00:00'): 27,
             Timestamp('2016-05-09 00:00:00'): 17,
             Timestamp('2016-05-10 00:00:00'): 34,
             Timestamp('2016-05-11 00:00:00'): 40,
             Timestamp('2016-05-12 00:00:00'): 40,
             Timestamp('2016-05-13 00:00:00'): 57,
             Timestamp('2016-05-14 00:00:00'): 19,
             Timestamp('2016-05-15 00:00:00'): 4,
             Timestamp('2016-05-16 00:00:00'): 29,
             Timestamp('2016-05-17 00:00:00'): 55,
             Timestamp('2016-05-18 00:00:00'): 55,
             Timestamp('2016-05-19 00:00:00'): 32,
             Timestamp('2016-05-20 00:00:00'): 33,
             Timestamp('2016-05-21 00:00:00'): 43,
             Timestamp('2016-05-22 00:00:00'): 7,
             Timestamp('2016-05-23 00:00:00'): 34,
             Timestamp('2016-05-24 00:00:00'): 65,
             Timestamp('2016-05-25 00:00:00'): 53,
             Timestamp('2016-05-26 00:00:00'): 41,
             Timestamp('2016-05-27 00:00:00'): 77,
             Timestamp('2016-05-28 00:00:00'): 11,
             Timestamp('2016-05-29 00:00:00'): 16,
             Timestamp('2016-05-30 00:00:00'): 12,
             Timestamp('2016-05-31 00:00:00'): 40,
             Timestamp('2016-06-01 00:00:00'): 32,
             Timestamp('2016-06-02 00:00:00'): 40,
             Timestamp('2016-06-03 00:00:00'): 13,
             Timestamp('2016-06-04 00:00:00'): 7,
             Timestamp('2016-06-05 00:00:00'): 2,
             Timestamp('2016-06-06 00:00:00'): 40,
             Timestamp('2016-06-07 00:00:00'): 57,
             Timestamp('2016-06-08 00:00:00'): 40,
             Timestamp('2016-06-09 00:00:00'): 96,
             Timestamp('2016-06-10 00:00:00'): 16,
             Timestamp('2016-06-11 00:00:00'): 13,
             Timestamp('2016-06-12 00:00:00'): 30,
             Timestamp('2016-06-13 00:00:00'): 34,
             Timestamp('2016-06-14 00:00:00'): 36,
             Timestamp('2016-06-15 00:00:00'): 22,
             Timestamp('2016-06-16 00:00:00'): 45,
             Timestamp('2016-06-17 00:00:00'): 65,
             Timestamp('2016-06-18 00:00:00'): 41,
             Timestamp('2016-06-19 00:00:00'): 11,
             Timestamp('2016-06-20 00:00:00'): 51,
             Timestamp('2016-06-21 00:00:00'): 66,
             Timestamp('2016-06-22 00:00:00'): 44,
             Timestamp('2016-06-23 00:00:00'): 29,
             Timestamp('2016-06-24 00:00:00'): 104,
             Timestamp('2016-06-25 00:00:00'): 157,
             Timestamp('2016-06-26 00:00:00'): 40,
             Timestamp('2016-06-27 00:00:00'): 47,
             Timestamp('2016-06-28 00:00:00'): 76,
             Timestamp('2016-06-29 00:00:00'): 57,
             Timestamp('2016-06-30 00:00:00'): 88,
             Timestamp('2016-07-01 00:00:00'): 57,
             Timestamp('2016-07-02 00:00:00'): 41,
             Timestamp('2016-07-03 00:00:00'): 10,
             Timestamp('2016-07-04 00:00:00'): 25,
             Timestamp('2016-07-05 00:00:00'): 33,
             Timestamp('2016-07-06 00:00:00'): 45,
             Timestamp('2016-07-07 00:00:00'): 67,
             Timestamp('2016-07-08 00:00:00'): 107,
             Timestamp('2016-07-09 00:00:00'): 24,
             Timestamp('2016-07-10 00:00:00'): 16,
             Timestamp('2016-07-11 00:00:00'): 49,
             Timestamp('2016-07-12 00:00:00'): 62,
             Timestamp('2016-07-13 00:00:00'): 43,
             Timestamp('2016-07-14 00:00:00'): 106,
             Timestamp('2016-07-15 00:00:00'): 61,
             Timestamp('2016-07-16 00:00:00'): 74,
             Timestamp('2016-07-17 00:00:00'): 13,
             Timestamp('2016-07-18 00:00:00'): 77,
             Timestamp('2016-07-19 00:00:00'): 56,
             Timestamp('2016-07-20 00:00:00'): 54,
             Timestamp('2016-07-21 00:00:00'): 53,
             Timestamp('2016-07-22 00:00:00'): 49,
             Timestamp('2016-07-23 00:00:00'): 24,
             Timestamp('2016-07-24 00:00:00'): 23,
             Timestamp('2016-07-25 00:00:00'): 120,
             Timestamp('2016-07-26 00:00:00'): 57,
             Timestamp('2016-07-27 00:00:00'): 77,
             Timestamp('2016-07-28 00:00:00'): 65,
             Timestamp('2016-07-29 00:00:00'): 45,
             Timestamp('2016-07-30 00:00:00'): 25,
             Timestamp('2016-07-31 00:00:00'): 35,
             Timestamp('2016-08-01 00:00:00'): 37,
             Timestamp('2016-08-02 00:00:00'): 77,
             Timestamp('2016-08-03 00:00:00'): 57,
             Timestamp('2016-08-04 00:00:00'): 38,
             Timestamp('2016-08-05 00:00:00'): 47,
             Timestamp('2016-08-06 00:00:00'): 10,
             Timestamp('2016-08-07 00:00:00'): 7,
             Timestamp('2016-08-08 00:00:00'): 37,
             Timestamp('2016-08-09 00:00:00'): 30,
             Timestamp('2016-08-10 00:00:00'): 54,
             Timestamp('2016-08-11 00:00:00'): 62,
             Timestamp('2016-08-12 00:00:00'): 50,
             Timestamp('2016-08-13 00:00:00'): 23,
             Timestamp('2016-08-14 00:00:00'): 23,
             Timestamp('2016-08-15 00:00:00'): 30,
             Timestamp('2016-08-16 00:00:00'): 47,
             Timestamp('2016-08-17 00:00:00'): 44,
             Timestamp('2016-08-18 00:00:00'): 41,
             Timestamp('2016-08-19 00:00:00'): 36,
             Timestamp('2016-08-20 00:00:00'): 29,
             Timestamp('2016-08-21 00:00:00'): 33,
             Timestamp('2016-08-22 00:00:00'): 28,
             Timestamp('2016-08-23 00:00:00'): 57,
             Timestamp('2016-08-24 00:00:00'): 88,
             Timestamp('2016-08-25 00:00:00'): 57,
             Timestamp('2016-08-26 00:00:00'): 98,
             Timestamp('2016-08-27 00:00:00'): 26,
             Timestamp('2016-08-28 00:00:00'): 13,
             Timestamp('2016-08-29 00:00:00'): 33,
             Timestamp('2016-08-30 00:00:00'): 82,
             Timestamp('2016-08-31 00:00:00'): 68,
             Timestamp('2016-09-01 00:00:00'): 140,
             Timestamp('2016-09-02 00:00:00'): 39,
             Timestamp('2016-09-03 00:00:00'): 36,
             Timestamp('2016-09-04 00:00:00'): 14,
             Timestamp('2016-09-05 00:00:00'): 11,
             Timestamp('2016-09-06 00:00:00'): 43,
             Timestamp('2016-09-07 00:00:00'): 57,
             Timestamp('2016-09-08 00:00:00'): 55,
             Timestamp('2016-09-09 00:00:00'): 41,
             Timestamp('2016-09-10 00:00:00'): 32,
             Timestamp('2016-09-11 00:00:00'): 9,
             Timestamp('2016-09-12 00:00:00'): 69,
             Timestamp('2016-09-13 00:00:00'): 45,
             Timestamp('2016-09-14 00:00:00'): 82,
             Timestamp('2016-09-15 00:00:00'): 53,
             Timestamp('2016-09-16 00:00:00'): 82,
             Timestamp('2016-09-17 00:00:00'): 45,
             Timestamp('2016-09-18 00:00:00'): 1,
             Timestamp('2016-09-19 00:00:00'): 27,
             Timestamp('2016-09-20 00:00:00'): 83,
             Timestamp('2016-09-21 00:00:00'): 48,
             Timestamp('2016-09-22 00:00:00'): 39,
             Timestamp('2016-09-23 00:00:00'): 40,
             Timestamp('2016-09-24 00:00:00'): 24,
             Timestamp('2016-09-25 00:00:00'): 5,
             Timestamp('2016-09-26 00:00:00'): 33,
             Timestamp('2016-09-27 00:00:00'): 55,
             Timestamp('2016-09-28 00:00:00'): 40,
             Timestamp('2016-09-29 00:00:00'): 34,
             Timestamp('2016-09-30 00:00:00'): 40,
             Timestamp('2016-10-01 00:00:00'): 62,
             Timestamp('2016-10-02 00:00:00'): 9,
             Timestamp('2016-10-03 00:00:00'): 36,
             Timestamp('2016-10-04 00:00:00'): 32,
             Timestamp('2016-10-05 00:00:00'): 48,
             Timestamp('2016-10-06 00:00:00'): 78,
             Timestamp('2016-10-07 00:00:00'): 45,
             Timestamp('2016-10-08 00:00:00'): 6,
             Timestamp('2016-10-09 00:00:00'): 5,
             Timestamp('2016-10-10 00:00:00'): 48,
             Timestamp('2016-10-11 00:00:00'): 46,
             Timestamp('2016-10-12 00:00:00'): 27,
             Timestamp('2016-10-13 00:00:00'): 64,
             Timestamp('2016-10-14 00:00:00'): 26,
             Timestamp('2016-10-15 00:00:00'): 6,
             Timestamp('2016-10-16 00:00:00'): 19,
             Timestamp('2016-10-17 00:00:00'): 30,
             Timestamp('2016-10-18 00:00:00'): 25,
             Timestamp('2016-10-19 00:00:00'): 66,
             Timestamp('2016-10-20 00:00:00'): 93,
             Timestamp('2016-10-21 00:00:00'): 50,
             Timestamp('2016-10-22 00:00:00'): 15,
             Timestamp('2016-10-23 00:00:00'): 21,
             Timestamp('2016-10-24 00:00:00'): 67,
             Timestamp('2016-10-25 00:00:00'): 50,
             Timestamp('2016-10-26 00:00:00'): 23,
             Timestamp('2016-10-27 00:00:00'): 56,
             Timestamp('2016-10-28 00:00:00'): 57,
             Timestamp('2016-10-29 00:00:00'): 25,
             Timestamp('2016-10-30 00:00:00'): 6,
             Timestamp('2016-10-31 00:00:00'): 18,
             Timestamp('2016-11-01 00:00:00'): 50,
             Timestamp('2016-11-02 00:00:00'): 41,
             Timestamp('2016-11-03 00:00:00'): 65,
             Timestamp('2016-11-04 00:00:00'): 42,
             Timestamp('2016-11-05 00:00:00'): 29,
             Timestamp('2016-11-06 00:00:00'): 24,
             Timestamp('2016-11-07 00:00:00'): 28,
             Timestamp('2016-11-08 00:00:00'): 60,
             Timestamp('2016-11-09 00:00:00'): 49,
             Timestamp('2016-11-10 00:00:00'): 92,
             Timestamp('2016-11-11 00:00:00'): 40,
             Timestamp('2016-11-12 00:00:00'): 9,
             Timestamp('2016-11-13 00:00:00'): 15,
             Timestamp('2016-11-14 00:00:00'): 27,
             Timestamp('2016-11-15 00:00:00'): 80,
             Timestamp('2016-11-16 00:00:00'): 63,
             Timestamp('2016-11-17 00:00:00'): 85,
             Timestamp('2016-11-18 00:00:00'): 52,
             Timestamp('2016-11-19 00:00:00'): 12,
             Timestamp('2016-11-20 00:00:00'): 10,
             Timestamp('2016-11-21 00:00:00'): 26,
             Timestamp('2016-11-22 00:00:00'): 40,
             Timestamp('2016-11-23 00:00:00'): 19,
             Timestamp('2016-11-24 00:00:00'): 31,
             Timestamp('2016-11-25 00:00:00'): 11,
             Timestamp('2016-11-26 00:00:00'): 11,
             Timestamp('2016-11-27 00:00:00'): 5,
             Timestamp('2016-11-28 00:00:00'): 51,
             Timestamp('2016-11-29 00:00:00'): 28,
             Timestamp('2016-11-30 00:00:00'): 10,
             Timestamp('2016-12-01 00:00:00'): 68,
             Timestamp('2016-12-02 00:00:00'): 27,
             Timestamp('2016-12-03 00:00:00'): 22,
             Timestamp('2016-12-04 00:00:00'): 31,
             Timestamp('2016-12-05 00:00:00'): 44,
             Timestamp('2016-12-06 00:00:00'): 55,
             Timestamp('2016-12-07 00:00:00'): 5,
             Timestamp('2016-12-16 00:00:00'): 114,
             Timestamp('2016-12-17 00:00:00'): 14,
             Timestamp('2016-12-18 00:00:00'): 14,
             Timestamp('2016-12-19 00:00:00'): 26,
             Timestamp('2016-12-20 00:00:00'): 19,
             Timestamp('2016-12-21 00:00:00'): 72,
             Timestamp('2016-12-22 00:00:00'): 62,
             Timestamp('2016-12-23 00:00:00'): 26,
             Timestamp('2016-12-24 00:00:00'): 9,
             Timestamp('2016-12-25 00:00:00'): 20,
             Timestamp('2016-12-26 00:00:00'): 4,
             Timestamp('2016-12-27 00:00:00'): 23,
             Timestamp('2016-12-28 00:00:00'): 10,
             Timestamp('2016-12-29 00:00:00'): 26,
             Timestamp('2016-12-30 00:00:00'): 15,
             Timestamp('2016-12-31 00:00:00'): 19,
             Timestamp('2017-01-01 00:00:00'): 8,
             Timestamp('2017-01-02 00:00:00'): 15,
             Timestamp('2017-01-03 00:00:00'): 10,
             Timestamp('2017-01-04 00:00:00'): 31,
             Timestamp('2017-01-05 00:00:00'): 28,
             Timestamp('2017-01-06 00:00:00'): 71,
             Timestamp('2017-01-07 00:00:00'): 13,
             Timestamp('2017-01-08 00:00:00'): 32,
             Timestamp('2017-01-09 00:00:00'): 104,
             Timestamp('2017-01-10 00:00:00'): 47,
             Timestamp('2017-01-11 00:00:00'): 87,
             Timestamp('2017-01-12 00:00:00'): 48,
             Timestamp('2017-01-13 00:00:00'): 134,
             Timestamp('2017-01-14 00:00:00'): 3,
             Timestamp('2017-01-15 00:00:00'): 12,
             Timestamp('2017-01-16 00:00:00'): 35,
             Timestamp('2017-01-17 00:00:00'): 101,
             Timestamp('2017-01-18 00:00:00'): 44,
             Timestamp('2017-01-19 00:00:00'): 121,
             Timestamp('2017-01-20 00:00:00'): 12,
             Timestamp('2017-01-21 00:00:00'): 23,
             Timestamp('2017-01-22 00:00:00'): 10,
             Timestamp('2017-01-23 00:00:00'): 21,
             Timestamp('2017-01-24 00:00:00'): 24,
             Timestamp('2017-01-25 00:00:00'): 60,
             Timestamp('2017-01-26 00:00:00'): 58,
             Timestamp('2017-01-27 00:00:00'): 234,
             Timestamp('2017-01-28 00:00:00'): 17,
             Timestamp('2017-01-29 00:00:00'): 37,
             Timestamp('2017-01-30 00:00:00'): 42,
             Timestamp('2017-01-31 00:00:00'): 78,
             Timestamp('2017-02-01 00:00:00'): 47,
             Timestamp('2017-02-02 00:00:00'): 64,
             Timestamp('2017-02-03 00:00:00'): 39,

In [210]:
# (positive - negative) sentiment counts of frequency of (positive - negative) keywords by day
sentbyday

defaultdict(int,
            {Timestamp('2016-01-01 00:00:00'): 17,
             Timestamp('2016-01-02 00:00:00'): 0,
             Timestamp('2016-01-03 00:00:00'): 30,
             Timestamp('2016-01-04 00:00:00'): -2,
             Timestamp('2016-01-05 00:00:00'): -8,
             Timestamp('2016-01-06 00:00:00'): -23,
             Timestamp('2016-01-07 00:00:00'): -5,
             Timestamp('2016-01-08 00:00:00'): -1,
             Timestamp('2016-01-09 00:00:00'): -9,
             Timestamp('2016-01-10 00:00:00'): 15,
             Timestamp('2016-01-11 00:00:00'): -1,
             Timestamp('2016-01-12 00:00:00'): 2,
             Timestamp('2016-01-13 00:00:00'): 8,
             Timestamp('2016-01-14 00:00:00'): 8,
             Timestamp('2016-01-15 00:00:00'): -23,
             Timestamp('2016-01-16 00:00:00'): 17,
             Timestamp('2016-01-17 00:00:00'): 14,
             Timestamp('2016-01-18 00:00:00'): -17,
             Timestamp('2016-01-19 00:00:00'): 12,
             Timestamp('2016-01-20 00:00:00'): 12,
             Timestamp('2016-01-21 00:00:00'): 15,
             Timestamp('2016-01-22 00:00:00'): 37,
             Timestamp('2016-01-23 00:00:00'): 9,
             Timestamp('2016-01-24 00:00:00'): 13,
             Timestamp('2016-01-25 00:00:00'): 11,
             Timestamp('2016-01-26 00:00:00'): 0,
             Timestamp('2016-01-27 00:00:00'): 6,
             Timestamp('2016-01-28 00:00:00'): 9,
             Timestamp('2016-01-29 00:00:00'): -3,
             Timestamp('2016-01-30 00:00:00'): 3,
             Timestamp('2016-01-31 00:00:00'): 6,
             Timestamp('2016-02-01 00:00:00'): -1,
             Timestamp('2016-02-02 00:00:00'): 7,
             Timestamp('2016-02-03 00:00:00'): 14,
             Timestamp('2016-02-04 00:00:00'): 6,
             Timestamp('2016-02-05 00:00:00'): 8,
             Timestamp('2016-02-06 00:00:00'): -4,
             Timestamp('2016-02-07 00:00:00'): -3,
             Timestamp('2016-02-08 00:00:00'): -4,
             Timestamp('2016-02-09 00:00:00'): 3,
             Timestamp('2016-02-10 00:00:00'): 12,
             Timestamp('2016-02-11 00:00:00'): -4,
             Timestamp('2016-02-12 00:00:00'): 16,
             Timestamp('2016-02-13 00:00:00'): -1,
             Timestamp('2016-02-14 00:00:00'): -2,
             Timestamp('2016-02-15 00:00:00'): 4,
             Timestamp('2016-02-16 00:00:00'): -6,
             Timestamp('2016-02-17 00:00:00'): 11,
             Timestamp('2016-02-18 00:00:00'): 11,
             Timestamp('2016-02-19 00:00:00'): 24,
             Timestamp('2016-02-20 00:00:00'): 2,
             Timestamp('2016-02-21 00:00:00'): -18,
             Timestamp('2016-02-22 00:00:00'): 4,
             Timestamp('2016-02-23 00:00:00'): 2,
             Timestamp('2016-02-24 00:00:00'): 15,
             Timestamp('2016-02-25 00:00:00'): 17,
             Timestamp('2016-02-26 00:00:00'): 4,
             Timestamp('2016-02-27 00:00:00'): 0,
             Timestamp('2016-02-28 00:00:00'): 2,
             Timestamp('2016-02-29 00:00:00'): 3,
             Timestamp('2016-03-01 00:00:00'): 16,
             Timestamp('2016-03-02 00:00:00'): 28,
             Timestamp('2016-03-03 00:00:00'): -6,
             Timestamp('2016-03-04 00:00:00'): -2,
             Timestamp('2016-03-05 00:00:00'): 11,
             Timestamp('2016-03-06 00:00:00'): 2,
             Timestamp('2016-03-07 00:00:00'): 1,
             Timestamp('2016-03-08 00:00:00'): -3,
             Timestamp('2016-03-09 00:00:00'): 6,
             Timestamp('2016-03-10 00:00:00'): 7,
             Timestamp('2016-03-11 00:00:00'): 8,
             Timestamp('2016-03-12 00:00:00'): 3,
             Timestamp('2016-03-13 00:00:00'): 13,
             Timestamp('2016-03-14 00:00:00'): -4,
             Timestamp('2016-03-15 00:00:00'): 15,
             Timestamp('2016-03-16 00:00:00'): -8,
             Timestamp('2016-03-17 00:00:00'): 22,
             Timestamp('2016-03-18 00:00:00'): 0,
             Timestamp('2016-03-19 00:00:00'): 6,
             Timestamp('2016-03-20 00:00:00'): 28,
             Timestamp('2016-03-21 00:00:00'): 15,
             Timestamp('2016-03-22 00:00:00'): 20,
             Timestamp('2016-03-23 00:00:00'): 12,
             Timestamp('2016-03-24 00:00:00'): -20,
             Timestamp('2016-03-25 00:00:00'): 0,
             Timestamp('2016-03-26 00:00:00'): 2,
             Timestamp('2016-03-27 00:00:00'): 18,
             Timestamp('2016-03-28 00:00:00'): 22,
             Timestamp('2016-03-29 00:00:00'): 55,
             Timestamp('2016-03-30 00:00:00'): -5,
             Timestamp('2016-03-31 00:00:00'): -8,
             Timestamp('2016-04-01 00:00:00'): 53,
             Timestamp('2016-04-02 00:00:00'): 8,
             Timestamp('2016-04-03 00:00:00'): 4,
             Timestamp('2016-04-04 00:00:00'): 23,
             Timestamp('2016-04-05 00:00:00'): 26,
             Timestamp('2016-04-06 00:00:00'): 21,
             Timestamp('2016-04-07 00:00:00'): 19,
             Timestamp('2016-04-08 00:00:00'): 19,
             Timestamp('2016-04-09 00:00:00'): 7,
             Timestamp('2016-04-10 00:00:00'): 1,
             Timestamp('2016-04-11 00:00:00'): 19,
             Timestamp('2016-04-12 00:00:00'): 39,
             Timestamp('2016-04-13 00:00:00'): 15,
             Timestamp('2016-04-14 00:00:00'): 8,
             Timestamp('2016-04-15 00:00:00'): -1,
             Timestamp('2016-04-16 00:00:00'): 0,
             Timestamp('2016-04-17 00:00:00'): 5,
             Timestamp('2016-04-18 00:00:00'): 31,
             Timestamp('2016-04-19 00:00:00'): -22,
             Timestamp('2016-04-20 00:00:00'): 7,
             Timestamp('2016-04-21 00:00:00'): 4,
             Timestamp('2016-04-22 00:00:00'): 11,
             Timestamp('2016-04-23 00:00:00'): 7,
             Timestamp('2016-04-24 00:00:00'): 11,
             Timestamp('2016-04-25 00:00:00'): 8,
             Timestamp('2016-04-26 00:00:00'): 27,
             Timestamp('2016-04-27 00:00:00'): 15,
             Timestamp('2016-04-28 00:00:00'): 5,
             Timestamp('2016-04-29 00:00:00'): 4,
             Timestamp('2016-04-30 00:00:00'): 4,
             Timestamp('2016-05-01 00:00:00'): 2,
             Timestamp('2016-05-02 00:00:00'): 20,
             Timestamp('2016-05-03 00:00:00'): 19,
             Timestamp('2016-05-04 00:00:00'): 26,
             Timestamp('2016-05-05 00:00:00'): 32,
             Timestamp('2016-05-06 00:00:00'): 16,
             Timestamp('2016-05-07 00:00:00'): 2,
             Timestamp('2016-05-08 00:00:00'): -9,
             Timestamp('2016-05-09 00:00:00'): 19,
             Timestamp('2016-05-10 00:00:00'): 23,
             Timestamp('2016-05-11 00:00:00'): 28,
             Timestamp('2016-05-12 00:00:00'): 10,
             Timestamp('2016-05-13 00:00:00'): 18,
             Timestamp('2016-05-14 00:00:00'): 10,
             Timestamp('2016-05-15 00:00:00'): 6,
             Timestamp('2016-05-16 00:00:00'): 16,
             Timestamp('2016-05-17 00:00:00'): 23,
             Timestamp('2016-05-18 00:00:00'): -8,
             Timestamp('2016-05-19 00:00:00'): -1,
             Timestamp('2016-05-20 00:00:00'): 18,
             Timestamp('2016-05-21 00:00:00'): 7,
             Timestamp('2016-05-22 00:00:00'): 4,
             Timestamp('2016-05-23 00:00:00'): 27,
             Timestamp('2016-05-24 00:00:00'): -9,
             Timestamp('2016-05-25 00:00:00'): 2,
             Timestamp('2016-05-26 00:00:00'): 32,
             Timestamp('2016-05-27 00:00:00'): -6,
             Timestamp('2016-05-28 00:00:00'): 6,
             Timestamp('2016-05-29 00:00:00'): 5,
             Timestamp('2016-05-30 00:00:00'): 30,
             Timestamp('2016-05-31 00:00:00'): 14,
             Timestamp('2016-06-01 00:00:00'): 30,
             Timestamp('2016-06-02 00:00:00'): -7,
             Timestamp('2016-06-03 00:00:00'): 2,
             Timestamp('2016-06-04 00:00:00'): 3,
             Timestamp('2016-06-05 00:00:00'): 12,
             Timestamp('2016-06-06 00:00:00'): 2,
             Timestamp('2016-06-07 00:00:00'): 78,
             Timestamp('2016-06-08 00:00:00'): 17,
             Timestamp('2016-06-09 00:00:00'): 0,
             Timestamp('2016-06-10 00:00:00'): 8,
             Timestamp('2016-06-11 00:00:00'): -2,
             Timestamp('2016-06-12 00:00:00'): -2,
             Timestamp('2016-06-13 00:00:00'): 26,
             Timestamp('2016-06-14 00:00:00'): -1,
             Timestamp('2016-06-15 00:00:00'): 11,
             Timestamp('2016-06-16 00:00:00'): 3,
             Timestamp('2016-06-17 00:00:00'): 4,
             Timestamp('2016-06-18 00:00:00'): -1,
             Timestamp('2016-06-19 00:00:00'): 3,
             Timestamp('2016-06-20 00:00:00'): -2,
             Timestamp('2016-06-21 00:00:00'): 24,
             Timestamp('2016-06-22 00:00:00'): 25,
             Timestamp('2016-06-23 00:00:00'): 6,
             Timestamp('2016-06-24 00:00:00'): -32,
             Timestamp('2016-06-25 00:00:00'): -32,
             Timestamp('2016-06-26 00:00:00'): 2,
             Timestamp('2016-06-27 00:00:00'): 4,
             Timestamp('2016-06-28 00:00:00'): 18,
             Timestamp('2016-06-29 00:00:00'): 14,
             Timestamp('2016-06-30 00:00:00'): 12,
             Timestamp('2016-07-01 00:00:00'): 14,
             Timestamp('2016-07-02 00:00:00'): 16,
             Timestamp('2016-07-03 00:00:00'): 6,
             Timestamp('2016-07-04 00:00:00'): 1,
             Timestamp('2016-07-05 00:00:00'): 1,
             Timestamp('2016-07-06 00:00:00'): 3,
             Timestamp('2016-07-07 00:00:00'): 36,
             Timestamp('2016-07-08 00:00:00'): -16,
             Timestamp('2016-07-09 00:00:00'): -5,
             Timestamp('2016-07-10 00:00:00'): 6,
             Timestamp('2016-07-11 00:00:00'): 12,
             Timestamp('2016-07-12 00:00:00'): 36,
             Timestamp('2016-07-13 00:00:00'): 12,
             Timestamp('2016-07-14 00:00:00'): 35,
             Timestamp('2016-07-15 00:00:00'): -13,
             Timestamp('2016-07-16 00:00:00'): -11,
             Timestamp('2016-07-17 00:00:00'): 4,
             Timestamp('2016-07-18 00:00:00'): 7,
             Timestamp('2016-07-19 00:00:00'): 71,
             Timestamp('2016-07-20 00:00:00'): 49,
             Timestamp('2016-07-21 00:00:00'): 25,
             Timestamp('2016-07-22 00:00:00'): 42,
             Timestamp('2016-07-23 00:00:00'): -2,
             Timestamp('2016-07-24 00:00:00'): 5,
             Timestamp('2016-07-25 00:00:00'): 5,
             Timestamp('2016-07-26 00:00:00'): 9,
             Timestamp('2016-07-27 00:00:00'): 47,
             Timestamp('2016-07-28 00:00:00'): 26,
             Timestamp('2016-07-29 00:00:00'): 20,
             Timestamp('2016-07-30 00:00:00'): 4,
             Timestamp('2016-07-31 00:00:00'): 1,
             Timestamp('2016-08-01 00:00:00'): -1,
             Timestamp('2016-08-02 00:00:00'): 26,
             Timestamp('2016-08-03 00:00:00'): -6,
             Timestamp('2016-08-04 00:00:00'): 11,
             Timestamp('2016-08-05 00:00:00'): 6,
             Timestamp('2016-08-06 00:00:00'): 4,
             Timestamp('2016-08-07 00:00:00'): 3,
             Timestamp('2016-08-08 00:00:00'): 17,
             Timestamp('2016-08-09 00:00:00'): 27,
             Timestamp('2016-08-10 00:00:00'): 18,
             Timestamp('2016-08-11 00:00:00'): 18,
             Timestamp('2016-08-12 00:00:00'): 17,
             Timestamp('2016-08-13 00:00:00'): 8,
             Timestamp('2016-08-14 00:00:00'): 3,
             Timestamp('2016-08-15 00:00:00'): 18,
             Timestamp('2016-08-16 00:00:00'): 76,
             Timestamp('2016-08-17 00:00:00'): 22,
             Timestamp('2016-08-18 00:00:00'): 18,
             Timestamp('2016-08-19 00:00:00'): 31,
             Timestamp('2016-08-20 00:00:00'): -2,
             Timestamp('2016-08-21 00:00:00'): 12,
             Timestamp('2016-08-22 00:00:00'): 19,
             Timestamp('2016-08-23 00:00:00'): 7,
             Timestamp('2016-08-24 00:00:00'): 26,
             Timestamp('2016-08-25 00:00:00'): -4,
             Timestamp('2016-08-26 00:00:00'): -1,
             Timestamp('2016-08-27 00:00:00'): 8,
             Timestamp('2016-08-28 00:00:00'): 6,
             Timestamp('2016-08-29 00:00:00'): 22,
             Timestamp('2016-08-30 00:00:00'): 0,
             Timestamp('2016-08-31 00:00:00'): -30,
             Timestamp('2016-09-01 00:00:00'): -7,
             Timestamp('2016-09-02 00:00:00'): 22,
             Timestamp('2016-09-03 00:00:00'): -1,
             Timestamp('2016-09-04 00:00:00'): 4,
             Timestamp('2016-09-05 00:00:00'): 8,
             Timestamp('2016-09-06 00:00:00'): 21,
             Timestamp('2016-09-07 00:00:00'): -4,
             Timestamp('2016-09-08 00:00:00'): 9,
             Timestamp('2016-09-09 00:00:00'): 11,
             Timestamp('2016-09-10 00:00:00'): 3,
             Timestamp('2016-09-11 00:00:00'): 2,
             Timestamp('2016-09-12 00:00:00'): -9,
             Timestamp('2016-09-13 00:00:00'): 14,
             Timestamp('2016-09-14 00:00:00'): -5,
             Timestamp('2016-09-15 00:00:00'): 22,
             Timestamp('2016-09-16 00:00:00'): 32,
             Timestamp('2016-09-17 00:00:00'): -12,
             Timestamp('2016-09-18 00:00:00'): 5,
             Timestamp('2016-09-19 00:00:00'): 4,
             Timestamp('2016-09-20 00:00:00'): 37,
             Timestamp('2016-09-21 00:00:00'): 23,
             Timestamp('2016-09-22 00:00:00'): 0,
             Timestamp('2016-09-23 00:00:00'): 13,
             Timestamp('2016-09-24 00:00:00'): -2,
             Timestamp('2016-09-25 00:00:00'): 0,
             Timestamp('2016-09-26 00:00:00'): 10,
             Timestamp('2016-09-27 00:00:00'): 51,
             Timestamp('2016-09-28 00:00:00'): 8,
             Timestamp('2016-09-29 00:00:00'): 6,
             Timestamp('2016-09-30 00:00:00'): 23,
             Timestamp('2016-10-01 00:00:00'): -14,
             Timestamp('2016-10-02 00:00:00'): -1,
             Timestamp('2016-10-03 00:00:00'): -12,
             Timestamp('2016-10-04 00:00:00'): 45,
             Timestamp('2016-10-05 00:00:00'): -3,
             Timestamp('2016-10-06 00:00:00'): 5,
             Timestamp('2016-10-07 00:00:00'): 35,
             Timestamp('2016-10-08 00:00:00'): 4,
             Timestamp('2016-10-09 00:00:00'): 2,
             Timestamp('2016-10-10 00:00:00'): -14,
             Timestamp('2016-10-11 00:00:00'): -19,
             Timestamp('2016-10-12 00:00:00'): 8,
             Timestamp('2016-10-13 00:00:00'): 20,
             Timestamp('2016-10-14 00:00:00'): 7,
             Timestamp('2016-10-15 00:00:00'): 14,
             Timestamp('2016-10-16 00:00:00'): 0,
             Timestamp('2016-10-17 00:00:00'): 3,
             Timestamp('2016-10-18 00:00:00'): -4,
             Timestamp('2016-10-19 00:00:00'): 3,
             Timestamp('2016-10-20 00:00:00'): -19,
             Timestamp('2016-10-21 00:00:00'): 3,
             Timestamp('2016-10-22 00:00:00'): 20,
             Timestamp('2016-10-23 00:00:00'): 16,
             Timestamp('2016-10-24 00:00:00'): 15,
             Timestamp('2016-10-25 00:00:00'): -9,
             Timestamp('2016-10-26 00:00:00'): 3,
             Timestamp('2016-10-27 00:00:00'): 4,
             Timestamp('2016-10-28 00:00:00'): 2,
             Timestamp('2016-10-29 00:00:00'): 0,
             Timestamp('2016-10-30 00:00:00'): 4,
             Timestamp('2016-10-31 00:00:00'): 0,
             Timestamp('2016-11-01 00:00:00'): -5,
             Timestamp('2016-11-02 00:00:00'): 10,
             Timestamp('2016-11-03 00:00:00'): 17,
             Timestamp('2016-11-04 00:00:00'): -12,
             Timestamp('2016-11-05 00:00:00'): 12,
             Timestamp('2016-11-06 00:00:00'): -7,
             Timestamp('2016-11-07 00:00:00'): 5,
             Timestamp('2016-11-08 00:00:00'): 14,
             Timestamp('2016-11-09 00:00:00'): 19,
             Timestamp('2016-11-10 00:00:00'): -22,
             Timestamp('2016-11-11 00:00:00'): 12,
             Timestamp('2016-11-12 00:00:00'): 9,
             Timestamp('2016-11-13 00:00:00'): 4,
             Timestamp('2016-11-14 00:00:00'): 18,
             Timestamp('2016-11-15 00:00:00'): 24,
             Timestamp('2016-11-16 00:00:00'): 17,
             Timestamp('2016-11-17 00:00:00'): 22,
             Timestamp('2016-11-18 00:00:00'): 31,
             Timestamp('2016-11-19 00:00:00'): 2,
             Timestamp('2016-11-20 00:00:00'): 3,
             Timestamp('2016-11-21 00:00:00'): -3,
             Timestamp('2016-11-22 00:00:00'): 21,
             Timestamp('2016-11-23 00:00:00'): 16,
             Timestamp('2016-11-24 00:00:00'): 9,
             Timestamp('2016-11-25 00:00:00'): 5,
             Timestamp('2016-11-26 00:00:00'): -2,
             Timestamp('2016-11-27 00:00:00'): 0,
             Timestamp('2016-11-28 00:00:00'): 10,
             Timestamp('2016-11-29 00:00:00'): 10,
             Timestamp('2016-11-30 00:00:00'): -4,
             Timestamp('2016-12-01 00:00:00'): -8,
             Timestamp('2016-12-02 00:00:00'): -3,
             Timestamp('2016-12-03 00:00:00'): 5,
             Timestamp('2016-12-04 00:00:00'): 21,
             Timestamp('2016-12-05 00:00:00'): 0,
             Timestamp('2016-12-06 00:00:00'): 16,
             Timestamp('2016-12-07 00:00:00'): 10,
             Timestamp('2016-12-16 00:00:00'): -19,
             Timestamp('2016-12-17 00:00:00'): -6,
             Timestamp('2016-12-18 00:00:00'): -2,
             Timestamp('2016-12-19 00:00:00'): 8,
             Timestamp('2016-12-20 00:00:00'): 11,
             Timestamp('2016-12-21 00:00:00'): -4,
             Timestamp('2016-12-22 00:00:00'): -3,
             Timestamp('2016-12-23 00:00:00'): 15,
             Timestamp('2016-12-24 00:00:00'): 0,
             Timestamp('2016-12-25 00:00:00'): 11,
             Timestamp('2016-12-26 00:00:00'): 4,
             Timestamp('2016-12-27 00:00:00'): 4,
             Timestamp('2016-12-28 00:00:00'): 5,
             Timestamp('2016-12-29 00:00:00'): -5,
             Timestamp('2016-12-30 00:00:00'): 10,
             Timestamp('2016-12-31 00:00:00'): 2,
             Timestamp('2017-01-01 00:00:00'): 0,
             Timestamp('2017-01-02 00:00:00'): 4,
             Timestamp('2017-01-03 00:00:00'): 2,
             Timestamp('2017-01-04 00:00:00'): 4,
             Timestamp('2017-01-05 00:00:00'): 3,
             Timestamp('2017-01-06 00:00:00'): 31,
             Timestamp('2017-01-07 00:00:00'): 7,
             Timestamp('2017-01-08 00:00:00'): 9,
             Timestamp('2017-01-09 00:00:00'): 16,
             Timestamp('2017-01-10 00:00:00'): 3,
             Timestamp('2017-01-11 00:00:00'): 6,
             Timestamp('2017-01-12 00:00:00'): 28,
             Timestamp('2017-01-13 00:00:00'): -10,
             Timestamp('2017-01-14 00:00:00'): 4,
             Timestamp('2017-01-15 00:00:00'): 0,
             Timestamp('2017-01-16 00:00:00'): 5,
             Timestamp('2017-01-17 00:00:00'): -11,
             Timestamp('2017-01-18 00:00:00'): 10,
             Timestamp('2017-01-19 00:00:00'): 5,
             Timestamp('2017-01-20 00:00:00'): 9,
             Timestamp('2017-01-21 00:00:00'): -1,
             Timestamp('2017-01-22 00:00:00'): 16,
             Timestamp('2017-01-23 00:00:00'): 13,
             Timestamp('2017-01-24 00:00:00'): 7,
             Timestamp('2017-01-25 00:00:00'): 5,
             Timestamp('2017-01-26 00:00:00'): 13,
             Timestamp('2017-01-27 00:00:00'): 16,
             Timestamp('2017-01-28 00:00:00'): -7,
             Timestamp('2017-01-29 00:00:00'): 3,
             Timestamp('2017-01-30 00:00:00'): 9,
             Timestamp('2017-01-31 00:00:00'): 0,
             Timestamp('2017-02-01 00:00:00'): 8,
             Timestamp('2017-02-02 00:00:00'): -5,
             Timestamp('2017-02-03 00:00:00'): 10,
             Timestamp('2017-02-04 00:00:00'): 29,
             Timestamp('2017-02-05 00:00:00'): 16,

In [211]:
# Create a dataframe of the positive sentiment counts of frequency of positive keywords by day
wsb_sentbydayposdf = pd.DataFrame([sentbydaypos]).transpose().reset_index()
wsb_sentbydayposdf.columns=(['Date','Pos_Count'])
wsb_sentbydayposdf

           Date  Pos_Count
0    2016-01-01         23
1    2016-01-02          2
2    2016-01-03         88
3    2016-01-04         28
4    2016-01-05         19
...         ...        ...
1916 2021-04-27       1137
1917 2021-04-28       1104
1918 2021-04-29        805
1919 2021-04-30       1187
1920 2021-05-01          6

[1921 rows x 2 columns]

In [212]:
wsb_sentbydayposdf.to_csv('./Data/wsb_sentbydayposdf_count.csv', index=False)

In [213]:
wsb_sentbydaynegdf = pd.DataFrame([sentbydayneg]).transpose().reset_index()
wsb_sentbydaynegdf.columns=(['Date','Neg_Count'])
wsb_sentbydaynegdf

           Date  Neg_Count
0    2016-01-01          6
1    2016-01-02          2
2    2016-01-03         58
3    2016-01-04         30
4    2016-01-05         27
...         ...        ...
1917 2021-04-27        617
1918 2021-04-28        600
1919 2021-04-29        462
1920 2021-04-30        894
1921 2021-05-01          4

[1922 rows x 2 columns]

In [214]:
wsb_sentbydaynegdf.to_csv('./Data/wsb_sentbydaynegdf_count.csv', index=False)

In [215]:
wsb_sentbydaydf = pd.DataFrame([sentbyday]).transpose().reset_index()
wsb_sentbydaydf.columns=(['Date','Sent_Count'])
wsb_sentbydaydf

           Date  Sent_Count
0    2016-01-01          17
1    2016-01-02           0
2    2016-01-03          30
3    2016-01-04          -2
4    2016-01-05          -8
...         ...         ...
1917 2021-04-27         520
1918 2021-04-28         504
1919 2021-04-29         343
1920 2021-04-30         293
1921 2021-05-01           2

[1922 rows x 2 columns]

In [216]:
wsb_sentbydaydf.to_csv('./Data/wsb_sentbydaydf_count.csv', index=False)

In [22]:
wsb_favw = WSB_reddits.loc[:, ["week", "favorites"]]
wsb_favw = wsb_favw.groupby(['week']).sum()
#wsb_favw = wsb_favw.loc[wsb_favw['week']>'2015-12-28']
wsb_favw

            favorites
week
2015-12-28        221
2016-01-04       2284
2016-01-11       3388
2016-01-18       3258
2016-01-25       2786
...               ...
2021-03-29       3100
2021-04-05       2222
2021-04-12       2126
2021-04-19       2130
2021-04-26       2389

[279 rows x 1 columns]

In [23]:
wsb_favw.to_csv('./Data/wsb_favw_count.csv', index=True)

In [25]:
wsb_favd

              day  favorites
27     2016-01-01          2
28     2016-01-01          8
32     2016-01-01          0
33     2016-01-01          1
34     2016-01-01          1
...           ...        ...
583002 2021-05-01          1
583016 2021-05-01          1
583026 2021-05-01          1
583030 2021-05-01          1
583031 2021-05-01          1

[264848 rows x 2 columns]

In [26]:
wsb_favd = WSB_reddits.loc[:, ["day", "favorites"]]
wsb_favd = wsb_favd.groupby(['day']).sum()
wsb_favd.rename(columns={"day": "date", "favorites": "favorites"}, inplace=True)
wsb_favd

            favorites
day
2016-01-01         25
2016-01-02         37
2016-01-03        159
2016-01-04        224
2016-01-05        156
...               ...
2021-04-27        558
2021-04-28        452
2021-04-29        455
2021-04-30        424
2021-05-01          6

[1922 rows x 1 columns]

In [27]:
wsb_favd.to_csv('./Data/wsb_favd_count.csv', index=True)